using BSI.Integra.Persistencia.Modelos.IntegraDB;
using BSI.Integra.Repositorio.Repository;
using BSI.Integra.Repositorio.Repository.Implementation;
using BSI.Integra.Repositorio.Repository.Interface;
using BSI.Integra.Repositorio.Repository.Interface.Comercial;
using BSI.Integra.Repositorio.Repository.Interface.Configuracion;
using BSI.Integra.Repositorio.Repository.Interface.Finanzas.Siigo;
using BSI.Integra.Repositorio.Repository.Interface.GestionPersonas;
using BSI.Integra.Repositorio.Repository.Interface.Marketing;
using BSI.Integra.Repositorio.Repository.Interface.Marketing.CampaniaMailingWhatsapp;
using BSI.Integra.Repositorio.Repository.Interface.Marketing.FacebookAudiencia;
using BSI.Integra.Repositorio.Repository.Interface.Marketing.FiltroSegmentoFolder;
using BSI.Integra.Repositorio.Repository.Interface.Marketing.FiltroSegmentoTipoContacto;
using BSI.Integra.Repositorio.Repository.Interface.Marketing.LinkedIn;
using BSI.Integra.Repositorio.Repository.Interface.Marketing.Melissa;
using BSI.Integra.Repositorio.Repository.Interface.Marketing.Sendingblue;
using BSI.Integra.Repositorio.Repository.Interface.Marketing.WhatsApp;
using BSI.Integra.Repositorio.Repository.Interface.Operacion;
using BSI.Integra.Repositorio.Repository.Interface.Operaciones;
using BSI.Integra.Repositorio.Repository.Interface.Planificacion;

namespace BSI.Integra.Repositorio.UnitOfWork
{
    public interface IUnitOfWork
    {
        void Commit();
        Task CommitAsync();
        void Rollback();
        void Dispose();
        void DetachAll();
        ICustomAuthenticationManagerRepository CustomAuthenticationManagerRepository { get; }
        IAreaTrabajoRepository AreaTrabajoRepository { get; }
        IAgendaTabRepository AgendaTabRepository { get; }
        IIntegraAspNetUserRepository IntegraAspNetUserRepository { get; }
        ISemaforoFinancieroRepository SemaforoFinancieroRepository { get; }
        ISemaforoFinancieroDetalleRepository SemaforoFinancieroDetalleRepository { get; }
        ISemaforoFinancieroVariableRepository SemaforoFinancieroVariableRepository { get; }
        ISemaforoFinancieroDetalleVariableRepository SemaforoFinancieroDetalleVariableRepository { get; }
        IProgramaGeneralProblemaRepository ProgramaGeneralProblemaRepository { get; }
        IPersonalRepository PersonalRepository { get; }
        IPGeneralRepository PGeneralRepository { get; }
        IEstadoOcurrenciaRepository EstadoOcurrenciaRepository { get; }
        ITableroComercialCategoriaAsesorRepository TableroComercialCategoriaAsesorRepository { get; }
        IFaseOportunidadRepository FaseOportunidadRepository { get; }
        IRecordAreaComercialRepository RecordAreaComercialRepository { get; }
        ITipoDatoRepository TipoDatoRepository { get; }
        IOrigenRepository OrigenRepository { get; }
        IAlumnoRepository AlumnoRepository { get; }
        IProbabilidadRegistroPwRepository ProbabilidadRegistroPwRepository { get; }
        ICategoriaOrigenRepository CategoriaOrigenRepository { get; }
        IEmpresaRepository EmpresaRepository { get; }
        ICiudadRepository CiudadRepository { get; }
        IGmailClienteRepository GmailClienteRepository { get; }
        IPlantillaRepository PlantillaRepository { get; }
        IGmailCorreoRepository GmailCorreoRepository { get; }
        IWhatsAppMensajeEnviadoRepository WhatsAppMensajeEnviadoRepository { get; }
        ICentroCostoRepository CentroCostoRepository { get; }
        IMatriculaCabeceraDatosCertificadoMensajeRepository MatriculaCabeceraDatosCertificadoMensajeRepository { get; }
        IPlantillaClaveValorRepository PlantillaClaveValorRepository { get; }
        IOportunidadLogRepository OportunidadLogRepository { get; }
        IMatriculaCabeceraRepository MatriculaCabeceraRepository { get; }
        IIndustriaRepository IndustriaRepository { get; }
        ISentinelRepository SentinelRepository { get; }
        IOportunidadRepository OportunidadRepository { get; }
        ISentinelRepLegItemRepository SentinelRepLegItemRepository { get; }
        ISentinelSdtEstandarItemRepository SentinelSdtEstandarItemRepository { get; }
        ISentinelSdtInfGenRepository SentinelSdtInfGenRepository { get; }
        ISentinelSdtLincreItemRepository SentinelSdtLincreItemRepository { get; }
        ISentinelSdtPoshisItemRepository SentinelSdtPoshisItemRepository { get; }
        ISentinelSdtRepSbsitemRepository SentinelSdtRepSbsitemRepository { get; }
        ISentinelSdtResVenItemRepository SentinelSdtResVenItemRepository { get; }
        ISentinelSueldoIndividualRepository SentinelSueldoIndividualRepository { get; }
        ISentinelSueldoPorIndustriaRepository SentinelSueldoPorIndustriaRepository { get; }
        ISentinelSueldoPorIndustriaDataDinamicoRepository SentinelSueldoPorIndustriaDataDinamicoRepository { get; }
        ISentinelSueldoPorIndustriaDataTotalRepository SentinelSueldoPorIndustriaDataTotalRepository { get; }
        IMonedaRepository MonedaRepository { get; }
        IAlumnoCuponRegistroRepository AlumnoCuponRegistroRepository { get; }
        ITiempoCapacitacionRepository TiempoCapacitacionRepository { get; }
        ICajaRepository CajaRepository { get; }
        ITipoImpuestoRepository TipoImpuestoRepository { get; }
        IRetencionRepository RetencionRepository { get; }
        ITipoServicioRepository TipoServicioRepository { get; }
        IEntidadFinancieraRepository EntidadFinancieraRepository { get; }
        ICuentaCorrienteRepository CuentaCorrienteRepository { get; }
        IEstadoMatriculaRepository EstadoMatriculaRepository { get; }
        ISubEstadoMatriculaRepository SubEstadoMatriculaRepository { get; }
        ICuentaContablePadreRepository CuentaContablePadreRepository { get; }
        ITipoCuentaBancoRepository TipoCuentaBancoRepository { get; }
        IEmpresaAutorizadaRepository EmpresaAutorizadaRepository { get; }
        IPlanContableRepository PlanContableRepository { get; }
        IProductoRepository ProductoRepository { get; }
        IDetraccionRepository DetraccionRepository { get; }
        IProveedorCalificacionRepository ProveedorCalificacionRepository { get; }
        IProveedorTipoServicioRepository ProveedorTipoServicioRepository { get; }
        IPrestacionRegistroRepository PrestacionRegistroRepository { get; }
        IProveedorCuentaBancoRepository ProveedorCuentaBancoRepository { get; }
        IProveedorSubCriterioCalificacionRepository ProveedorSubCriterioCalificacionRepository { get; }
        IDocumentoIdentidadRepository DocumentoIdentidadRepository { get; }
        IProveedorCriterioCalificacionRepository ProveedorCriterioCalificacionRepository { get; }
        ITipoContribuyenteRepository TipoContribuyenteRepository { get; }
        IProductoPresentacionRepository ProductoPresentacionRepository { get; }
        ICompetidorRepository CompetidorRepository { get; }
        IDetalleOportunidadCompetidorRepository DetalleOportunidadCompetidorRepository { get; }
        IMandrilRepository MandrilRepository { get; }
        IProgramaGeneralBeneficioArgumentoRepository ProgramaGeneralBeneficioArgumentoRepository { get; }
        IHistoricoProductoProveedorRepository HistoricoProductoProveedorRepository { get; }

        IMontoPagoCronogramaRepository MontoPagoCronogramaRepository { get; }
        IMontoPagoCronogramaDetalleRepository MontoPagoCronogramaDetalleRepository { get; }
        IPasarelaPagoPwRepository PasarelaPagoPwRepository { get; }
        IPEspecificoRepository PEspecificoRepository { get; }
        IPaisRepository PaisRepository { get; }
        ISeguimientoAlumnoComentarioRepository SeguimientoAlumnoComentarioRepository { get; }
        ISeguimientoAlumnoDetalleRepository SeguimientoAlumnoDetalleRepository { get; }
        IDocumentacionComercialPwRepository DocumentacionComercialPwRepository { get; }
        IDocumentoSeccionPwRepository DocumentoSeccionPwRepository { get; }
        ICronogramaPagoDetalleFinalRepository CronogramaPagoDetalleFinalRepository { get; }
        IPgeneralAsubPgeneralRepository PgeneralAsubPgeneralRepository { get; }
        IMatriculaCabeceraBeneficiosRepository MatriculaCabeceraBeneficiosRepository { get; }
        IConfiguracionBeneficioProgramaGeneralRepository ConfiguracionBeneficioProgramaGeneralRepository { get; }
        IPreguntaFrecuentePGeneralRepository PreguntaFrecuentePGeneralRepository { get; }
        IOcurrenciaActividadAlternoRepository OcurrenciaActividadAlternoRepository { get; }
        IAlumnoLogRepository AlumnoLogRepository { get; }
        IDocumentoLegalRepository DocumentoLegalRepository { get; }
        IPersonalAreaTrabajoRepository PersonalAreaTrabajoRepository { get; }
        ICargoRepository CargoRepository { get; }
        IOportunidadMaximaPorCategoriaRepository OportunidadMaximaPorCategoriaRepository { get; }
        IMaterialVersionRepository MaterialVersionRepository { get; }
        IDocumentoOportunidadRepository DocumentoOportunidadRepository { get; }
        IAreaFormacionRepository AreaFormacionRepository { get; }
        IAreaCapacitacionRepository AreaCapacitacionRepository { get; }
        ISubAreaCapacitacionRepository SubAreaCapacitacionRepository { get; }
        IPGeneralTipoDescuentoRepository PGeneralTipoDescuentoRepository { get; }
        IDocumentoOportunidadTipoRepository DocumentoOportunidadTipoRepository { get; }
        IPlantillaBaseRepository PlantillaBaseRepository { get; }
        IDocumentoLegalAreaTrabajoRepository DocumentoLegalAreaTrabajoRepository { get; }
        IDocumentoLegalPaisRepository DocumentoLegalPaisRepository { get; }
        IWhatsAppPlantillaPorOcurrenciaActividadRepository WhatsAppPlantillaPorOcurrenciaActividadRepository { get; }
        IWhatsAppEstadoMensajeEnviadoRepository WhatsAppEstadoMensajeEnviadoRepository { get; }
        IChatDetalleIntegraRepository ChatDetalleIntegraRepository { get; }
        IChatDetalleIntegraArchivoRepository ChatDetalleIntegraArchivoRepository { get; }
        ICondicionPagoRepository CondicionPagoRepository { get; }
        ICondicionTipoPagoRepository CondicionTipoPagoRepository { get; }
        ITipoCambioMonedumRepository TipoCambioMonedumRepository { get; }
        ITipoCambioRepository TipoCambioRepository { get; }
        ITipoCambioColRepository TipoCambioColRepository { get; }
        IPeriodoRepository PeriodoRepository { get; }
        IProveedorRepository ProveedorRepository { get; }
        IProgramaGeneralCertificacionRepository ProgramaGeneralCertificacionRepository { get; }
        IProgramaGeneralCertificacionArgumentoRepository ProgramaGeneralCertificacionArgumentoRepository { get; }
        IProgramaGeneralMotivacionRepository ProgramaGeneralMotivacionRepository { get; }
        IProgramaGeneralMotivacionArgumentoRepository ProgramaGeneralMotivacionArgumentoRepository { get; }
        IClasificacionPersonaRepository ClasificacionPersonaRepository { get; }
        IProgramaGeneralProblemaDetalleSolucionRepository ProgramaGeneralProblemaDetalleSolucionRepository { get; }
        IProgramaGeneralPrerequisitoRepository ProgramaGeneralPrerequisitoRepository { get; }
        IProgramaGeneralBeneficioRepository ProgramaGeneralBeneficioRepository { get; }
        IOportunidadCompetidorRepository OportunidadCompetidorRepository { get; }
        ITipoDescuentoRepository TipoDescuentoRepository { get; }
        IMontoPagoRepository MontoPagoRepository { get; }
        IOperadorComparacionRepository OperadorComparacionRepository { get; }
        IConfiguracionFijaRepository ConfiguracionFijaRepository { get; }
        ITableroComercialUnidadRepository TableroComercialUnidadRepository { get; }
        IDocumentoAgendaRepository DocumentoAgendaRepository { get; }
        IMedioPagoMatriculaCronogramaRepository MedioPagoMatriculaCronogramaRepository { get; }
        IProgramaGeneralProblemaModalidadRepository ProgramaGeneralProblemaModalidadRepository { get; }
        ICronogramaPagoRepository CronogramaPagoRepository { get; }
        IModalidadCursoRepository ModalidadCursoRepository { get; }
        IPlantillaPwRepository PlantillaPwRepository { get; }
        IVersionProgramaRepository VersionProgramaRepository { get; }
        IPGeneralDocumentoPwRepository PGeneralDocumentoPwRepository { get; }
        IEtiquetaRepository EtiquetaRepository { get; }
        IPgeneralParametroSeoPwRepository PGeneralParametroSeoPwRepository { get; }
        ITipoCategoriaOrigenRepository TipoCategoriaOrigenRepository { get; }
        IProcedenciaFormularioRepository ProcedenciaFormularioRepository { get; }
        IProcedenciaFormularioDetalleRepository ProcedenciaFormularioDetalleRepository { get; }
        ITipoInteraccionRepository TipoInteraccionRepository { get; }

        IExcepcionFrecuenciaPwRepository ExcepcionFrecuenciaPwRepository { get; }
        IPersonalHorarioRepository PersonalHorarioRepository { get; }
        IReprogramacionCabeceraRepository ReprogramacionCabeceraRepository { get; }
        ITiempoLibreRepository TiempoLibreRepository { get; }
        IHoraBloqueadaRepository HoraBloqueadaRepository { get; }
        IPersonaRepository PersonaRepository { get; }

        IOcurrenciaRepository OcurrenciaRepository { get; }
        IOportunidadRemarketingAgendaRepository OportunidadRemarketingAgendaRepository { get; }
        IPreCalculadaCambioFaseRepository PreCalculadaCambioFaseRepository { get; }
        IActividadDetalleRepository ActividadDetalleRepository { get; }
        IComprobantePagoOportunidadRepository ComprobantePagoOportunidadRepository { get; }
        IReprogramacionCabeceraPersonalRepository ReprogramacionCabeceraPersonalRepository { get; }
        IProgramaGeneralBeneficioRespuestaRepository ProgramaGeneralBeneficioRespuestaRepository { get; }
        IProgramaGeneralMotivacionRespuestaRepository ProgramaGeneralMotivacionRespuestaRepository { get; }
        IPublicoObjetivoRespuestaRepository PublicoObjetivoRespuestaRepository { get; }
        IProgramaGeneralCertificacionRespuestaRepository ProgramaGeneralCertificacionRespuestaRepository { get; }
        IProgramaGeneralProblemaDetalleSolucionRespuestaRepository ProgramaGeneralProblemaDetalleSolucionRespuestaRepository { get; }
        IProgramaGeneralPrerequisitoRespuestaRepository ProgramaGeneralPrerequisitoRespuestaRepository { get; }
        IDocumentoEnviadoWebPwRepository DocumentoEnviadoWebPwRepository { get; }
        ICalidadLlamadaLogRepository CalidadLlamadaLogRepository { get; }
        IOcurrenciaAlternoRepository OcurrenciaAlternoRepository { get; }
        ISmsConfiguracionEnvioRepository SmsConfiguracionEnvioRepository { get; }
        IPartnerPwRepository PartnerPwRepository { get; }
        IGradoEstudioRepository GradoEstudioRepository { get; }
        INivelCompetenciaTecnicaRepository NivelCompetenciaTecnicaRepository { get; }
        ICentroEstudioRepository CentroEstudioRepository { get; }
        ITipoCentroEstudioRepository TipoCentroEstudioRepository { get; }
        ITipoExperienciaRepository TipoExperienciaRepository { get; }
        IExpositorRepository ExpositorRepository { get; }
        IMessengerChatRepository MessengerChatRepository { get; }
        IOrigenDatoCalidadDetalleRepository OrigenDatoCalidadDetalleRepository { get; }
        IOrigenSectorRepository OrigenSectorRepository { get; }
        IOrigenDatoCalidadRepository OrigenDatoCalidadRepository { get; }
        IOportunidadConfiguradoRepository OportunidadConfiguradoRepository { get; }
        IOportunidadPreAsignadumRepository OportunidadPreAsignadumRepository { get; }
        IOportunidadErradoRepository OportunidadErradoRepository { get; }





        IInteraccionRepository InteraccionRepository { get; }
        IMandrilEnvioCorreoRepository MandrilEnvioCorreoRepository { get; }
        IGmailCorreoArchivoAdjuntoRepository GmailCorreoArchivoAdjuntoRepository { get; }
        IConfigurarVideoProgramaRepository ConfigurarVideoProgramaRepository { get; }
        IEstructuraEspecificaRepository EstructuraEspecificaRepository { get; }
        IProveedorCampaniaIntegraRepository ProveedorCampaniaIntegraRepository { get; }
        ICampoContactoRepository CampoContactoRepository { get; }
        ICampaniaGeneralRepository CampaniaGeneralRepository { get; }
        ICampaniaGeneralDetalleRepository CampaniaGeneralDetalleRepository { get; }
        ICampaniaGeneralDetalleSubAreaRepositorio CampaniaGeneralDetalleSubAreaRepositorio { get; }
        ICampaniaGeneralDetalleProgramaRepositorio CampaniaGeneralDetalleProgramaRepositorio { get; }
        IRegistroArchivoStorageRepository RegistroArchivoStorageRepository { get; }
        IUrlBlockStorageRepository UrlBlockStorageRepository { get; }
        IUrlSubContenedorRepository UrlSubContenedorRepository { get; }
        IFormularioSolicitudRepository FormularioSolicitudRepository { get; }
        IFormularioRespuestaRepository FormularioRespuestaRepository { get; }
        IFormularioSolicitudTextoBotonRepository FormularioSolicitudTextoBotonRepository { get; }


        IAvatarRepository AvatarRepository { get; }
        IDataCreditoBusquedumRepository DataCreditoBusquedumRepository { get; }
        IDataCreditoLogRepository DataCreditoLogRepository { get; }
        IDataCreditoDataNaturalNacionalRepository DataCreditoDataNaturalNacionalRepository { get; }
        IDataCreditoDataScoreRepository DataCreditoDataScoreRepository { get; }
        IDataCreditoDataCuentaAhorroRepository DataCreditoDataCuentaAhorroRepository { get; }
        IDataCreditoDataTarjetaCreditoRepository DataCreditoDataTarjetaCreditoRepository { get; }
        IDataCreditoDataCuentaCarteraRepository DataCreditoDataCuentaCarteraRepository { get; }
        IDataCreditoConsultumRepository DataCreditoConsultumRepository { get; }
        IDataCreditoDataEndeudamientoGlobalRepository DataCreditoDataEndeudamientoGlobalRepository { get; }
        IDataCreditoDataProductoValorRepository DataCreditoDataProductoValorRepository { get; }
        IDataCreditoDataInfAgrResumenPrincipalRepository DataCreditoDataInfAgrResumenPrincipalRepository { get; }
        IDataCreditoDataInfAgrResumenSaldoRepository DataCreditoDataInfAgrResumenSaldoRepository { get; }
        IDataCreditoDataInfAgrResumenSaldoSectorRepository DataCreditoDataInfAgrResumenSaldoSectorRepository { get; }
        IDataCreditoDataInfAgrResumenSaldoMeRepository DataCreditoDataInfAgrResumenSaldoMeRepository { get; }
        IDataCreditoDataInfAgrResumenComportamientoRepository DataCreditoDataInfAgrResumenComportamientoRepository { get; }
        IDataCreditoDataInfAgrTotalRepository DataCreditoDataInfAgrTotalRepository { get; }
        IDataCreditoDataInfAgrComposicionPortafolioRepository DataCreditoDataInfAgrComposicionPortafolioRepository { get; }
        IDataCreditoDataInfAgrEvolucionDeudaTrimestreRepository DataCreditoDataInfAgrEvolucionDeudaTrimestreRepository { get; }
        IDataCreditoDataInfAgrEvolucionDeudaAnalisisPromedioRepository DataCreditoDataInfAgrEvolucionDeudaAnalisisPromedioRepository { get; }
        IDataCreditoDataInfAgrHistoricoSaldoTipoCuentumRepository DataCreditoDataInfAgrHistoricoSaldoTipoCuentumRepository { get; }
        IDataCreditoDataInfAgrHistoricoSaldoTotalRepository DataCreditoDataInfAgrHistoricoSaldoTotalRepository { get; }
        IDataCreditoDataInfAgrResumenEndeudamientoRepository DataCreditoDataInfAgrResumenEndeudamientoRepository { get; }
        IDataCreditoDataInfMicroPerfilGeneralRepository DataCreditoDataInfMicroPerfilGeneralRepository { get; }
        IDataCreditoDataInfMicroVectorSaldoMoraRepository DataCreditoDataInfMicroVectorSaldoMoraRepository { get; }
        IDataCreditoDataInfMicroEndeudamientoActualRepository DataCreditoDataInfMicroEndeudamientoActualRepository { get; }
        IDataCreditoDataInfMicroImagenTendenciaEndeudamientoRepository DataCreditoDataInfMicroImagenTendenciaEndeudamientoRepository { get; }
        IDataCreditoDataInfMicroAnalisisVectorRepository DataCreditoDataInfMicroAnalisisVectorRepository { get; }
        IDataCreditoDataInfMicroEvolucionDeudumRepository DataCreditoDataInfMicroEvolucionDeudumRepository { get; }
        INotaIngresoCajaRepository NotaIngresoCajaRepository { get; }
        IOrigenIngresoCajaRepository OrigenIngresoCajaRepository { get; }
        IContactoConfiguracionRepository ContactoConfiguracionRepository { get; }
        IReferidoConfiguracionRepository ReferidoConfiguracionRepository { get; }
        ICajaPorRendirRepository CajaPorRendirRepository { get; }
        ICajaPorRendirCabeceraRepository CajaPorRendirCabeceraRepository { get; }
        IFurRepository FurRepository { get; }
        ICampoFormularioRepository CampoFormularioRepository { get; }
        IConjuntoAnuncioRepository ConjuntoAnuncioRepository { get; }
        IFuentesPortalWebRepository FuentesPortalWebRepository { get; }
        IEstilosCssRepository EstilosCssRepository { get; }
        ITagsRepository TagsRepository { get; }
        ITagsEstiloRepository TagsEstiloRepository { get; }
        ITipoLandingPageRepository TipoLandingPageRepository { get; }
        IPlantillaV2Repository PlantillaV2Repository { get; }
        ISeccionRepository SeccionRepository { get; }
        IPlantillaV2SeccionRepository PlantillaV2SeccionRepository { get; }
        IPlantillaV2SeccionEstiloRepository PlantillaV2SeccionEstiloRepository { get; }
        ILandingPageRepository LandingPageRepository { get; }
        IRegionCiudadRepository RegionCiudadRepository { get; }
        IProgramaGeneralModeloCertificadoRepository ProgramaGeneralModeloCertificadoRepository { get; }
        IReporteRepository ReportesRepository { get; }
        IWhatsAppConfiguracionRepository WhatsAppConfiguracionRepository { get; }
        IWhatsAppUsuarioCredencialRepository WhatsAppUsuarioCredencialRepository { get; }
        IInteraccionChatIntegraRepository InteraccionChatIntegraRepository { get; }
        IMoodleCronogramaEvaluacionRepository MoodleCronogramaEvaluacionRepository { get; }
        IMensajeTextoRepository MensajeTextoRepository { get; }
        IConfiguracionDatoRemarketingRepository ConfiguracionDatoRemarketingRepository { get; }
        IConfiguracionDatoRemarketingTipoDatoRepository ConfiguracionDatoRemarketingTipoDatoRepository { get; }
        IConfiguracionDatoRemarketingTipoCategoriaOrigenRepository ConfiguracionDatoRemarketingTipoCategoriaOrigenRepository { get; }

        IProcedenciaVentaCruzadumRepository ProcedenciaVentaCruzadumRepository { get; }
        ICampaniaMailingDetalleRepository CampaniaMailingDetalleRepository { get; }
        IAsignacionOportunidadRepository AsignacionOportunidadRepository { get; }
        IAsignacionOportunidadLogRepository AsignacionOportunidadLogRepository { get; }
        IModeloDataMiningRepository ModeloDataMiningRepository { get; }
        ILogRepository LogRepository { get; }
        ICriterioCalificacionRepository CriterioCalificacionRepository { get; }

        IConfiguracionDatoRemarketingCategoriaOrigenRepository ConfiguracionDatoRemarketingCategoriaOrigenRepository { get; }
        IConfiguracionDatoRemarketingProbabilidadRegistroRepository ConfiguracionDatoRemarketingProbabilidadRegistroRepository { get; }
        IGrupoFiltroProgramaCriticoRepository GrupoFiltroProgramaCriticoRepository { get; }
        IGrupoFiltroProgramaCriticoPorAsesorRepository GrupoFiltroProgramaCriticoPorAsesorRepository { get; }
        IGrupoFiltroProgramaCriticoPgeneralRepository GrupoFiltroProgramaCriticoPgeneralRepository { get; }
        IPuntoCorteRepository PuntoCorteRepository { get; }
        IProgramaGeneralPuntoCorteRepository ProgramaGeneralPuntoCorteRepository { get; }
        IProgramaGeneralPuntoCorteConfiguracionRepository ProgramaGeneralPuntoCorteConfiguracionRepository { get; }
        IProgramaGeneralPuntoCorteDetalleRepository ProgramaGeneralPuntoCorteDetalleRepository { get; }
        ICajaEgresoAprobadoRepository CajaEgresoAprobadoRepository { get; }
        ICajaEgresoRepository CajaEgresoRepository { get; }
        IComprobantePagoPorFurRepository ComprobantePagoPorFurRepository { get; }
        IFurPagoRepository FurPagoRepository { get; }
        IComprobantePagoRepository ComprobantePagoRepository { get; }
        IModoFurRepository ModoFurRepository { get; }
        IModoPersonalFurRepository ModoPersonalFurRepository { get; }
        IFurFaseAprobacionRepository FurFaseAprobacionRepository { get; }
        IFurTipoPedidoRepository FurTipoPedidoRepository { get; }
        IBloqueHorarioRepository BloqueHorarioRepository { get; }
        ITroncalPgeneralRepository TroncalPgeneralRepository { get; }
        IPgeneralConfiguracionPlantillaDetalleRepository PgeneralConfiguracionPlantillaDetalleRepository { get; }
        IPgeneralCodigoPartnerRepository PgeneralCodigoPartnerRepository { get; }
        IPgeneralCodigoPartnerVersionProgramaRepository PgeneralCodigoPartnerVersionProgramaRepository { get; }
        IPgeneralCodigoPartnerModalidadCursoRepository PgeneralCodigoPartnerModalidadCursoRepository { get; }
        IPgeneralProyectoAplicacionRepository PgeneralProyectoAplicacionRepository { get; }

        IPgeneralProyectoAplicacionModalidadRepository PgeneralProyectoAplicacionModalidadRepository { get; }
        IPgeneralProyectoAplicacionProveedorRepository PgeneralProyectoAplicacionProveedorRepository { get; }
        IPgeneralCriterioEvaluacionHijoRepository PgeneralCriterioEvaluacionHijoRepository { get; }
        IPgeneralForoAsignacionProveedorRepository PgeneralForoAsignacionProveedorRepository { get; }
        IPostulanteRepository PostulanteRepository { get; }
        IChatIntegraHistorialAsesorRepository ChatIntegraHistorialAsesorRepository { get; }
        IWhatsAppMensajeRecibidoRepository WhatsAppMensajeRecibidoRepository { get; }
        ILlamadaWebphoneAsteriskRepository LlamadaWebphoneAsteriskRepository { get; }
        IControlDocAlumnoRepository ControlDocAlumnoRepository { get; }
        IBeneficioAlumnoPEspecificoRepository BeneficioAlumnoPEspecificoRepository { get; }
        IConfiguracionAsignacionCoordinadorOportunidadOperacionRepository ConfiguracionAsignacionCoordinadorOportunidadOperacionRepository { get; }
        IPaisConfiguracionAsignacionRegularRepository PaisConfiguracionAsignacionRegularRepository { get; }
        IPaisAsignacionRegularRepository PaisAsignacionRegularRepository { get; }
        IAsignacionRegularRepository AsignacionRegularRepository { get; }
        IArticuloRepository ArticuloRepository { get; }
        ITipoArticuloRepository TipoArticuloRepository { get; }
        IArticuloSeoRepository ArticuloSeoRepository { get; }
        ICategoriaProgramaRepository CategoriaProgramaRepository { get; }
        ITagRepository TagRepository { get; }
        IArticuloTagRepository ArticuloTagRepository { get; }
        IArticuloPGeneralRepository ArticuloPGeneralRepository { get; }
        IOportunidadIsVerificadaRepository OportunidadIsVerificadaRepository { get; }
        ISolicitudCertificadoFisicoRepository SolicitudCertificadoFisicoRepository { get; }
        IPEspecificoSesionRepository PEspecificoSesionRepository { get; }
        IOportunidadClasificacionOperacionesRepository OportunidadClasificacionOperacionesRepository { get; }
        ISolicitudOperacionesRepository SolicitudOperacionesRepository { get; }
        IAsignacionAutomaticaRepository AsignacionAutomaticaRepository { get; }
        IAsignacionAutomaticaErrorRepository AsignacionAutomaticaErrorRepository { get; }
        IRemitenteMailingRepository RemitenteMailingRepository { get; }
        IRemitenteMailingAsesorRepository RemitenteMailingAsesorRepository { get; }
        IBeneficioLaboralTipoRepository BeneficioLaboralTipoRepository { get; }
        IBeneficioLaboralPorPeriodoRepository BeneficioLaboralPorPeriodoRepository { get; }
        IReporteComisionMatriculaRepository ReporteComisionMatriculaRepository { get; }
        ISendingblueRelacionAlumnoSbRepository sendingblueRelacionAlumnoSbRepository { get; }
        ISendinblueAtributoRepository sendinblueAtributoRepository { get; }
        ISendinblueCampaniaRepository sendinblueCampaniaRepository { get; }
        ISendinblueCarpetaRepository sendinblueCarpetaRepository { get; }
        ISendinblueContactoRepository sendinblueContactoRepository { get; }
        ISendinblueListaRepository sendinblueListaRepository { get; }
        IFiltroSegmentoSendinBlueRepository filtroSegmentoSendinBlueRepository { get; }
        IUsuarioRepository UsuarioRepository { get; }
        ICorreoGmailRepository CorreoGmailRepository { get; }
        IConfiguracionEnvioMailingRepository ConfiguracionEnvioMailingRepository { get; }
        IReclamoRepository ReclamoRepository { get; }
        ITarifarioDetalleAlternoRepository TarifarioDetalleAlternoRepository { get; }
        IEstadoCertificadoFisicoRepository EstadoCertificadoFisicoRepository { get; }
        ISeguimientoAlumnoCategoriaRepository SeguimientoAlumnoCategoriaRepository { get; }
        ICategoriaAlumnoRepository CategoriaAlumnoRepository { get; }
        IEsquemaEvaluacionRepository EsquemaEvaluacionRepository { get; }
        INotaRepository NotaRepository { get; }
        IRecuperacionSesionRepository RecuperacionSesionRepository { get; }
        IEvaluacionEscalaCalificacionRepository EvaluacionEscalaCalificacionRepository { get; }
        IPEspecificoMatriculaAlumnoRepository PEspecificoMatriculaAlumnoRepository { get; }
        IAsesorChatRepository AsesorChatRepository { get; }
        IAsesorChatDetalleRepository AsesorChatDetalleRepository { get; }
        ICampaniasMailingWhatsappRepository campaniasMailingWhatsappRepository { get; }
        ICampaniaWhatsappFiltradoRepository campaniaWhatsappFiltradoRepository { get; }
        ICampaniaMailingFiltradoRepositorio campaniaMailingFiltradoRepositorioa { get; }
        ICampaniaGeneralRepositorio campaniaGeneralRepositorio { get; }
        IPGeneralConfiguracionPlantillaRepository PGeneralConfiguracionPlantillaRepository { get; }
        ICertificadoGeneradoAutomaticoRepository CertificadoGeneradoAutomaticoRepository { get; }
        ICertificadoGeneradoAutomaticoContenidoRepository CertificadoGeneradoAutomaticoContenidoRepository { get; }
        IRegistroCertificadoFisicoGeneradoRepository RegistroCertificadoFisicoGeneradoRepository { get; }

        ITarifarioRepository TarifarioRepository { get; }
        IAdworkCredencialApiRepository AdworkCredencialApiRepository { get; }

        IAdwordsApiPalabraClaveRepository AdwordsApiPalabraClaveRepository { get; }

        IAdwordsApiVolumenBusquedumRepository AdwordsApiVolumenBusquedumRepository { get; }
        IFacebookFormularioLeadgenRepository FacebookFormularioLeadgenRepository { get; }
        IAsignacionAutomaticaTempRepository AsignacionAutomaticaTempRepository { get; }
        IAsignacionAutomaticaConfiguracionRepository AsignacionAutomaticaConfiguracionRepository { get; }
        IBloqueHorarioProcesaOportunidadRepository BloqueHorarioProcesaOportunidadRepository { get; }
        IModeloPredictivoProbabilidadRepository ModeloPredictivoProbabilidadRepository { get; }


        ICalidadProcesamientoRepository CalidadProcesamientoRepository { get; }
        IOportunidadPrerequisitoGeneralRepository OportunidadPrerequisitoGeneralRepository { get; }
        IOportunidadPrerequisitoEspecificoRepository OportunidadPrerequisitoEspecificoRepository { get; }
        ISolucionClienteByActividadRepository SolucionClienteByActividadRepository { get; }
        IOportunidadBeneficioRepository OportunidadBeneficioRepository { get; }
        IAreaCampaniaGeneralDetalleRepository areaCampaniaGeneralDetalleRepository { get; }
        ICampaniaGeneralDetalleResponsableRepositorio campaniaGeneralDetalleResponsableRepositorio { get; }
        IMatriculaCabeceraDatosCertificadoRepository MatriculaCabeceraDatosCertificadoRepository { get; }
        IErrorRepository ErrorRepository { get; }
        IWhatsAppNumeroValidadoRepository WhatsAppNumeroValidadoRepository { get; }
        IWhatsAppDesuscritoRepository WhatsAppDesuscritoRepository { get; }
        ITipoIdentificadorRepository TipoIdentificadorRepository { get; }
        ITamanioEmpresaRepository TamanioEmpresaRepository { get; }
        ICodigoCiiuIndustriaRepository CodigoCiiuIndustriaRepository { get; }
        ICompromisoAlumnoRepository CompromisoAlumnoRepository { get; }
        ITipoReclamoAlumnoRepository TipoReclamoAlumnoRepository { get; }
        IPanelIngresoDisponibleRepository PanelIngresoDisponibleRepository { get; }
        IDiaSemanaRepository DiaSemanaRepository { get; }
        IFormaPagoRepository FormaPagoRepository { get; }
        IOcurrenciaActividadRepository OcurrenciaActividadRepository { get; }
        IConfiguracionEnvioAutomaticoRepository ConfiguracionEnvioAutomaticoRepository { get; }
        ITipoEnvioAutomaticoRepository TipoEnvioAutomaticoRepository { get; }
        IConfiguracionEnvioAutomaticoDetalleRepository ConfiguracionEnvioAutomaticoDetalleRepository { get; }
        IOtroMovimientoCajaRepository OtroMovimientoCajaRepository { get; }
        ITipoMovimientoCajaRepository TipoMovimientoCajaRepository { get; }
        ISubTipoMovimientoCajaRepository SubTipoMovimientoCajaRepository { get; }

        INuevoAlumnoCongeladoRepository NuevoAlumnoCongeladoRepository { get; }
        ISolicitudTipoReporteRepository SolicitudTipoReporteRepository { get; }
        IControlSolicitudOrigenRepository ControlSolicitudOrigenRepository { get; }
        IEstadoSolicitudBeneficioRepository EstadoSolicitudBeneficioRepository { get; }
        ISolicitudSubCategoriaRepository SolicitudSubCategoriaRepository { get; }
        ISolicitudCategoriaRepository SolicitudCategoriaRepository { get; }
        ISolicitudAlumnoRepository SolicitudAlumnoRepository { get; }
        ISolicitudInternaRepository SolicitudInternaRepository { get; }

        IWhatsAppConfiguracionEnvioRepository WhatsAppConfiguracionEnvioRepository { get; }
        IWhatsAppConfiguracionEnvioPorProgramaRepository WhatsAppConfiguracionEnvioPorProgramaRepository { get; }
        IRegistroRecuperacionWhatsAppRepository RegistroRecuperacionWhatsAppRepository { get; }
        IWhatsAppConfiguracionLogEjecucionRepository WhatsAppConfiguracionLogEjecucionRepository { get; }
        IConfiguracionEnvioMailingDetalleRepository ConfiguracionEnvioMailingDetalleRepository { get; }
        IFiltradoDeDatosPorPrioridadWhatsAppRepository FiltradoDeDatosPorPrioridadWhatsAppRepository { get; }
        IPersonalEncargadoDeEnvioDeConsultumRepository PersonalEncargadoDeEnvioDeConsultumRepository { get; }
        IConfiguracionDeEnvioParaWhatsAppRepository ConfiguracionDeEnvioParaWhatsAppRepository { get; }
        IWhatsAppMensajePublicidadRepository WhatsAppMensajePublicidadRepository { get; }
        IRecuperacionAutomaticoModuloSistemaRepository RecuperacionAutomaticoModuloSistemaRepository { get; }
        IWhatsAppConfiguracionPreEnvioRepository WhatsAppConfiguracionPreEnvioRepository { get; }

        IWhatsAppConfiguracionEnvioDetalleRepository WhatsAppConfiguracionEnvioDetalleRepository { get; }
        IConjuntoListaResultadoRepository ConjuntoListaResultadoRepository { get; }
        ISolicitudOperacionesAccesoTemporalDetalleRepository SolicitudOperacionesAccesoTemporalDetalleRepository { get; }
        ISolicitudRepository SolicitudRepository { get; }
        IAnuncioFacebookMetricaRepository AnuncioFacebookMetricaRepository { get; }
        IFacebookCuentaPublicitariaRepository FacebookCuentaPublicitariaRepository { get; }
        IInteraccionPaginaRepository InteraccionPaginaRepository { get; }
        ICampaniaFacebookRepository CampaniaFacebookRepository { get; }
        IConjuntoAnuncioFacebookRepository ConjuntoAnuncioFacebookRepository { get; }
        IAnuncioFacebookRepository AnuncioFacebookRepository { get; }
        IAutenticacionServicioExternoRepository AutenticacionServicioExternoRepository { get; }
        IGastoFinancieroCronogramaRepository GastoFinancieroCronogramaRepository { get; }
        IGastoFinancieroCronogramaDetalleRepository GastoFinancieroCronogramaDetalleRepository { get; }
        ICertificadoSolicitudRepository CertificadoSolicitudRepository { get; }
        ICertificadoTipoRepository CertificadoTipoRepository { get; }
        ICertificadoTipoProgramaRepository CertificadoTipoProgramaRepository { get; }
        ISedeRepository SedeRepository { get; }
        ITipoComprobanteRepository TipoComprobanteRepository { get; }
        IFurTipoSolicitudRepository FurTipoSolicitudRepository { get; }
        IEstadoPagoMatriculaRepository EstadoPagoMatriculaRepository { get; }
        IDocumentoPagoRepository DocumentoPagoRepository { get; }
        IControlDocRepository ControlDocRepository { get; }
        ICriterioDocRepository CriterioDocRepository { get; }
        ICronogramaDetalleCambioRepository CronogramaDetalleCambioRepository { get; }
        ICronogramaCabeceraCambioRepository CronogramaCabeceraCambioRepository { get; }
        ICronogramaPagoDetalleModLogFinalRepository CronogramaPagoDetalleModLogFinalRepository { get; }
        ICronogramaPagoDetalleModRepository CronogramaPagoDetalleModRepository { get; }
        ICronogramaPagoDetalleOriginalRepository CronogramaPagoDetalleOriginalRepository { get; }
        IMatriculaDetalleRepository MatriculaDetalleRepository { get; }
        ICronogramaPagoDetalleRepository CronogramaPagoDetalleRepository { get; }
        IPagoFinalRepository PagoFinalRepository { get; }
        IPagoRepository PagoRepository { get; }
        IReporteTipoDeCambioFinancieroMensualRepository ReporteTipoDeCambioFinancieroMensualRepository { get; }
        IVerificacionManualDatosRepository VerificacionManualDatosRepository { get; }
        IFiltroSegmentoTipoContactoRepository FiltroSegmentoTipoContactoRepository { get; }
        ITipoFormularioRepository TipoFormularioRepository { get; }
        ITiempoFrecuenciaRepository TiempoFrecuenciaRepository { get; }
        IEstadoActividadDetalleRepository EstadoActividadDetalleRepository { get; }
        IEmbudoNivelRepository EmbudoNivelRepository { get; }
        IActividadCabeceraRepository ActividadCabeceraRepository { get; }
        ILogFiltroSegmentoEjecutadoRepository LogFiltroSegmentoEjecutadoRepository { get; }
        IFacebookAudienciaRepository FacebookAudienciaRepository { get; }
        IActividadCrepLogRepository ActividadCrepLogRepository { get; }
        ITipoCambioEntreMonedaRepository TipoCambioEntreMonedaRepository { get; }
        IPespecificoPadrePespecificoHijoRepository PespecificoPadrePespecificoHijoRepository { get; }
        IFiltroSegmentoRepository FiltroSegmentoRepository { get; }
        IFiltroSegmentoValorTipoRepository FiltroSegmentoValorTipoRepository { get; }
        IFiltroSegmentoDetalleRepository FiltroSegmentoDetalleRepository { get; }
        IFeriadoRepository FeriadoRepository { get; }
        ISeccionPreguntaFrecuenteRepository SeccionPreguntaFrecuenteRepository { get; }
        IPreguntaFrecuenteAreaRepository PreguntaFrecuenteAreaRepository { get; }
        IPreguntaFrecuenteSubAreaRepository PreguntaFrecuenteSubAreaRepository { get; }
        IPreguntaFrecuenteTipoRepository PreguntaFrecuenteTipoRepository { get; }
        IPreguntaFrecuenteRepository PreguntaFrecuenteRepository { get; }
        IFacebookAudienciumRepository FacebookAudienciumRepository { get; }
        IFacebookAudienciaAlumnoRepository FacebookAudienciaAlumnoRepository { get; }
        IFacebookAudienciaCuentaPublicitariumRepository FacebookAudienciaCuentaPublicitariumRepository { get; }
        IConfiguracionProyeccionFurRepository ConfiguracionProyeccionFurRepository { get; }
        IPeriodoMesProyeccionRepository PeriodoMesProyeccionRepository { get; }
        IEstadoProyeccionFurRepository EstadoProyeccionFurRepository { get; }
        ICabeceraFurConfiguracionAutomaticaRepository CabeceraFurConfiguracionAutomaticaRepository { get; }
        IFurConfiguracionAutomaticaRepository FurConfiguracionAutomaticaRepository { get; }
        IFrecuenciaRepository FrecuenciaRepository { get; }
        ILogProyeccionFurRepository LogProyeccionFurRepository { get; }
        ISendinBlueDataDeEventoRepository SendinBlueDataDeEventoRepository { get; }
        ISendinBlueEventoWebHookRepository SendinBlueEventoWebHookRepository { get; }
        ILlamadaWebphoneCruceCentralRepository LlamadaWebphoneCruceCentralRepository { get; }
        ICongelamientoProyeccionFurRepository CongelamientoProyeccionFurRepository { get; }
        IReporteResumenMontoRepository ReporteResumenMontoRepository { get; }
        ISendinblueRelacionListaContactoEmailRepository SendinblueRelacionListaContactoEmailRepository { get; }
        IEstructuraEspecificaTareaRepository EstructuraEspecificaTareaRepository { get; }
        IMaterialAccionRepository MaterialAccionRepository { get; }
        IMaterialCriterioVerificacionRepository MaterialCriterioVerificacionRepository { get; }
        IReporteLibroReclamacionRepository ReporteLibroReclamacionRepository { get; }
        IMoodleCategoriaTipoRepository MoodleCategoriaTipoRepository { get; }
        IMoodleCategoriaRepository MoodleCategoriaRepository { get; }
        IParametroSeoPwRepository ParametroSeoPwRepository { get; }
        IReporteControlTareaAlumnoRepository ReporteControlTareaAlumnoRepository { get; }
        IReporteProblemasAulaVirtualRepository ReporteProblemasAulaVirtualRepository { get; }
        IReporteEncuestasRepository ReporteEncuestasRepository { get; }
        IReporteEncuestasSincronicoRepository ReporteEncuestasSincronicoRepository { get; }
        IAmbienteRepository AmbienteRepository { get; }
        IOrigenProgramaRepository OrigenProgramaRepository { get; }
        ILocacionRepository LocacionRepository { get; }
        IEstadoPespecificoRepository EstadoPespecificoRepository { get; }
        IAreaCcRepository AreaCentroCostoRepository { get; }
        ICriterioEvaluacionCategoriumRepository CriterioEvaluacionCategoriumRepository { get; }
        IEvaluacionCategoriumRepository EvaluacionCategoriumRepository { get; }
        IAreaParametroSeoPwRepository AreaParametroSeoPwRepository { get; }
        ISubAreaParametroSeoPwRepository SubAreaParametroSeoPwRepository { get; }
        ISubNivelCcRepository SubNivelCcRepository { get; }
        IDiferenciaHorariaRepository DiferenciaHorariaRepository { get; }
        IPespecificoCronogramaRepository PespecificoCronogramaRepository { get; }
        IPespecificoCronogramaGrupoRepository PespecificoCronogramaGrupoRepository { get; }
        ICursoPespecificoRepository CursoPespecificoRepository { get; }
        IFormulaTipoDescuentoRepository FormulaTipoDescuentoRepository { get; }
        IAgendaTipoUsuarioRepository AgendaTipoUsuarioRepository { get; }
        ITipoDescuentoAsesorCoordinadorPwRepository TipoDescuentoAsesorCoordinadorPwRepository { get; }
        IFeedbackTipoRepository FeedbackTipoRepository { get; }
        ITipoDocumentoAlumnoRepository TipoDocumentoAlumnoRepository { get; }
        ITipoDocumentoAlumnoModalidadCursoRepository TipoDocumentoAlumnoModalidadCursoRepository { get; }
        ITipoDocumentoAlumnoEstadoMatriculaRepository TipoDocumentoAlumnoEstadoMatriculaRepository { get; }
        ITipoDocumentoAlumnoSubEstadoMatriculaRepository TipoDocumentoAlumnoSubEstadoMatriculaRepository { get; }
        ITipoDocumentoAlumnoPgeneralRepository TipoDocumentoAlumnoPgeneralRepository { get; }
        IMaterialEstadoRepository MaterialEstadoRepository { get; }
        IMoodleCursoRepository MoodleCursoRepository { get; }
        ITipoPersonaRepository TipoPersonaRepository { get; }
        IMaterialTipoRepository MaterialTipoRepository { get; }
        IMaterialAsociacionAccionRepository MaterialAsociacionAccionRepository { get; }
        IMaterialAsociacionVersionRepository MaterialAsociacionVersionRepository { get; }
        IMaterialAsociacionCriterioVerificacionRepository MaterialAsociacionCriterioVerificacionRepository { get; }
        IEscalaCalificacionRepository EscalaCalificacionRepository { get; }
        IEscalaCalificacionDetalleRepository EscalaCalificacionDetalleRepository { get; }


        ITagPwRepository TagPwRepository { get; }
        IPgeneralTagsPwRepository PgeneralTagsPwRepository { get; }
        IDescuentoPromocionRepository DescuentoPromocionRepository { get; }
        IFeedbackConfigurarGrupoPreguntaRepository FeedbackConfigurarGrupoPreguntaRepository { get; }
        IFeedbackGrupoPreguntaProgramaEspecificoRepository FeedbackGrupoPreguntaProgramaEspecificoRepository { get; }
        IFeedbackGrupoPreguntaProgramaGeneralRepository FeedbackGrupoPreguntaProgramaGeneralRepository { get; }
        IConjuntoListaRepository ConjuntoListaRepository { get; }
        IConjuntoListaDetalleRepository ConjuntoListaDetalleRepository { get; }
        IConjuntoListaDetalleValorRepository ConjuntoListaDetalleValorRepository { get; }
        IModuloSistemaV5Repository ModuloSistemaV5Repository { get; }
        IFaseByPlantillaRepository FaseByPlantillaRepository { get; }
        ICategoriaCiudadRepository CategoriaCiudadRepository { get; }
        IPespecificoParticipacionExpositorRepository PespecificoParticipacionExpositorRepository { get; }
        IPespecificoFrecuenciaRepository PespecificoFrecuenciaRepository { get; }
        IConfigurarWebinarRepository ConfigurarWebinarRepository { get; }
        IPespecificoPadreFrecuenciaRepository PespecificoPadreFrecuenciaRepository { get; }
        IPEspecificoPadreFrecuenciaSesionRepository PEspecificoPadreFrecuenciaSesionRepository { get; }
        IFeedbackConfigurarRepository FeedbackConfigurarRepository { get; }
        IPespecificoFrecuenciaDetalleRepository PespecificoFrecuenciaDetalleRepository { get; }
        IFormaCalificacionEvaluacionRepository FormaCalificacionEvaluacionRepository { get; }
        ITipoProgramaRepository TipoProgramaRepository { get; }
        ICriterioEvaluacionRepository CriterioEvaluacionRepository { get; }
        IParametroEvaluacionRepository ParametroEvaluacionRepository { get; }
        ICriterioEvaluacionModalidadCursoRepository CriterioEvaluacionModalidadCursoRepository { get; }
        ICriterioEvaluacionTipoPersonaRepository CriterioEvaluacionTipoPersonaRepository { get; }
        ICriterioEvaluacionTipoProgramaRepository CriterioEvaluacionTipoProgramaRepository { get; }
        IMaterialAdicionalAulaVirtualRepository MaterialAdicionalAulaVirtualRepository { get; }
        IVisualizacionBsPlayRepository VisualizacionBsPlayRepository { get; }
        ITituloRepository TituloRepository { get; }
        IPerfilContactoProgramaColumnaRepository PerfilContactoProgramaColumnaRepository { get; }
        IPaginaWebPwRepository PaginaWebPwRepository { get; }
        IProgramaGeneralPerfilScoringCiudadRepository ProgramaGeneralPerfilScoringCiudadRepository { get; }
        IProgramaGeneralPerfilScoringModalidadRepository ProgramaGeneralPerfilScoringModalidadRepository { get; }
        IProgramaGeneralPerfilScoringAformacionRepository ProgramaGeneralPerfilScoringAformacionRepository { get; }
        IProgramaGeneralPerfilScoringIndustriaRepository ProgramaGeneralPerfilScoringIndustriaRepository { get; }
        ISuscripcionProgramaGeneralRepository SuscripcionProgramaGeneralRepository { get; }
        ITipoPagoRepository TipoPagoRepository { get; }
        IPlataformaPagoRepository PlataformaPagoRepository { get; }
        IPEspecificoConsumoRepository PEspecificoConsumoRepository { get; }
        IProgramaGeneralPerfilScoringCargoRepository ProgramaGeneralPerfilScoringCargoRepository { get; }
        IProgramaGeneralPerfilScoringAtrabajoRepository ProgramaGeneralPerfilScoringAtrabajoRepository { get; }
        IProgramaGeneralPerfilScoringCategoriaRepository ProgramaGeneralPerfilScoringCategoriaRepository { get; }
        IProgramaGeneralPerfilModalidadCoeficienteRepository ProgramaGeneralPerfilModalidadCoeficienteRepository { get; }
        IProgramaGeneralPerfilCiudadCoeficienteRepository ProgramaGeneralPerfilCiudadCoeficienteRepository { get; }
        IProgramaGeneralPerfilCategoriaCoeficienteRepository ProgramaGeneralPerfilCategoriaCoeficienteRepository { get; }
        IProgramaGeneralPerfilCargoCoeficienteRepository ProgramaGeneralPerfilCargoCoeficienteRepository { get; }
        IProgramaGeneralPerfilIndustriaCoeficienteRepository ProgramaGeneralPerfilIndustriaCoeficienteRepository { get; }
        IProgramaGeneralPerfilAformacionCoeficienteRepository ProgramaGeneralPerfilAformacionCoeficienteRepository { get; }
        IProgramaGeneralPerfilAtrabajoCoeficienteRepository ProgramaGeneralPerfilAtrabajoCoeficienteRepository { get; }
        IProgramaGeneralPerfilTipoDatoRepository ProgramaGeneralPerfilTipoDatoRepository { get; }
        IProgramaGeneralPerfilEscalaProbabilidadRepository ProgramaGeneralPerfilEscalaProbabilidadRepository { get; }
        IProgramaGeneralPerfilInterceptoRepository ProgramaGeneralPerfilInterceptoRepository { get; }
        IBeneficioDatoAdicionalRepository BeneficioDatoAdicionalRepository { get; }
        IPGeneralVersionProgramaRepository PGeneralVersionProgramaRepository { get; }
        IConvocatoriaPersonalRepository ConvocatoriaPersonalRepository { get; }
        IFormaCalculoEvaluacionRepository FormaCalculoEvaluacionRepository { get; }
        IModeloPredictivoEscalaProbabilidadRepository ModeloPredictivoEscalaProbabilidadRepository { get; }
        IModeloPredictivoTipoDatoRepository ModeloPredictivoTipoDatoRepository { get; }
        IModeloPredictivoIndustriaRepository ModeloPredictivoIndustriaRepository { get; }
        IModeloPredictivoCargoRepository ModeloPredictivoCargoRepository { get; }
        IModeloPredictivoFormacionRepository ModeloPredictivoFormacionRepository { get; }
        IModeloPredictivoTrabajoRepository ModeloPredictivoTrabajoRepository { get; }
        IModeloPredictivoCategoriaDatoRepository ModeloPredictivoCategoriaDatoRepository { get; }
        IModeloGeneralRepository ModeloGeneralRepository { get; }
        IModeloGeneralPGeneralRepository ModeloGeneralPGeneralRepository { get; }
        IModeloPredictivoRepository ModeloPredictivoRepository { get; }
        IPgeneralProyectoAplicacionAnexoRepository PgeneralProyectoAplicacionAnexoRepository { get; }
        IDocumentoPwRepository DocumentoPwRepository { get; }
        IPGeneralRelacionadoRepository PGeneralRelacionadoRepository { get; }
        IPlantillaAsociacionModuloSistemaRepository PlantillaAsociacionModuloSistemaRepository { get; }
        IWhatsAppEstadoValidacionRepository WhatsAppEstadoValidacionRepository { get; }
        ISeguimientoPreProcesoListaWhatsAppRepository SeguimientoPreProcesoListaWhatsAppRepository { get; }
        IActividadCabeceraDiaSemanaRepository ActividadCabeceraDiaSemanaRepository { get; }
        IMaterialAdicionalAulaVirtualRegistroRepository MaterialAdicionalAulaVirtualRegistroRepository { get; }
        IMaterialAdicionalAulaVirtualPespecificoRepository MaterialAdicionalAulaVirtualPespecificoRepository { get; }
        IProgramaGeneralMaterialEstudioAdicionalRepository ProgramaGeneralMaterialEstudioAdicionalRepository { get; }
        IProgramaGeneralMaterialEstudioAdicionalEspecificoRepository ProgramaGeneralMaterialEstudioAdicionalEspecificoRepository { get; }
        IPGeneralCriterioEvaluacionRepository PGeneralCriterioEvaluacionRepository { get; }
        IProgramaGeneralPrerequisitoModalidadRepository ProgramaGeneralPrerequisitoModalidadRepository { get; }
        IPGeneralDescripcionRepository PGeneralDescripcionRepository { get; }
        IAdicionalProgramaGeneralRepository AdicionalProgramaGeneralRepository { get; }
        IPGeneralExpositorRepository PGeneralExpositorRepository { get; }
        IPGeneralModalidadRepository PGeneralModalidadRepository { get; }
        IProgramaAreaRelacionadaRepository ProgramaAreaRelacionadaRepository { get; }
        ITipoPagoCategoriaRepository TipoPagoCategoriaRepository { get; }
        IMontoPagoPlataformaRepository MontoPagoPlataformaRepository { get; }
        IMontoPagoSuscripcionRepository MontoPagoSuscripcionRepository { get; }
        ISedeTrabajoRepository SedeTrabajoRepository { get; }
        IProcesoSeleccionRepository ProcesoSeleccionRepository { get; }
        IEstadoConvocatoriaRepository EstadoConvocatoriaRepository { get; }
        IModalidadTrabajoRepository ModalidadTrabajoRepository { get; }
        ICategoriaAsignacionRepository CategoriaAsignacionRepository { get; }
        IExperienciaRepository ExperienciaRepository { get; }
        INivelEstudioRepository NivelEstudioRepository { get; }
        IIdiomaRepository IdiomaRepository { get; }
        ITipoContratoRepository TipoContratoRepository { get; }
        IPlantillaMaestroPwRepository PlantillaMaestroPwRepository { get; }
        IRevisionPwRepository RevisionPwRepository { get; }
        ISeccionTipoContenidoPwRepository SeccionTipoContenidoPwRepository { get; }
        IEsquemaEvaluacionPgeneralRepository EsquemaEvaluacionPgeneralRepository { get; }
        IEsquemaEvaluacionPgeneralModalidadRepository EsquemaEvaluacionPgeneralModalidadRepository { get; }
        IEsquemaEvaluacionPgeneralProveedorRepository EsquemaEvaluacionPgeneralProveedorRepository { get; }
        IRevisionNivelPwRepository RevisionNivelPwRepository { get; }
        ISeccionPwRepository SeccionPwRepository { get; }
        ICourierRepository CourierRepository { get; }
        ICourierDetalleRepository CourierDetalleRepository { get; }
        IPlantillaPaisRepository PlantillaPaisRepository { get; }
        ISeccionTipoDetallePwRepository SeccionTipoDetallePwRepository { get; }
        IMaterialPespecificoRepository MaterialPespecificoRepository { get; }
        IMaterialPespecificoDetalleRepository MaterialPespecificoDetalleRepository { get; }
        ITroncalCiudadRepository TroncalCiudadRepository { get; }
        IAreaRepository AreaRepository { get; }
        ISubAreaRepository SubAreaRepository { get; }
        IActividadMarcadorLogRepository ActividadMarcadorLogRepository { get; }
        IPreguntaProgramaCapacitacionRepository PreguntaProgramaCapacitacionRepository { get; }
        ITipoVistumRepository TipoVistumRepository { get; }
        ITipoEvaluacionTrabajoRepository TipoEvaluacionTrabajoRepository { get; }
        ITipoMarcadorRepository TipoMarcadorRepository { get; }
        ISesionConfigurarVideoRepository SesionConfigurarVideoRepository { get; }
        ITagParametroSeoPwRepository TagParametroSeoPwRepository { get; }
        IConfigurarEvaluacionTrabajoRepository ConfigurarEvaluacionTrabajoRepository { get; }
        IPreguntaEvaluacionTrabajoRepository PreguntaEvaluacionTrabajoRepository { get; }
        IPreguntaEncuestaCategoriaRepository PreguntaEncuestaCategoriaRepository { get; }
        IPreguntaEncuestaRepository PreguntaEncuestaRepository { get; }
        IPreguntaEncuestaRespuestaRepository PreguntaEncuestaRespuestaRepository { get; }
        IPreguntaEncuestaOnlineRepository PreguntaEncuestaOnlineRepository { get; }
        IEncuestaOnlineRepository EncuestaOnlineRepository { get; }
        ITipoEncuestumRepository TipoEncuestumRepository { get; }
        IEncuestaSesionProgramaRepository EncuestaSesionProgramaRepository { get; }
        ICampaniaGeneralWhatsAppRepository CampaniaGeneralWhatsAppRepository { get; }
        IPlantillaSendinblueImagenRepository PlantillaSendinblueImagenRepository { get; }
        IPlantillaSendinblueBaseRepository PlantillaSendinblueBaseRepository { get; }
        IPlantillaSendinblueEtiquetaPlantillaRepository PlantillaSendinblueEtiquetaPlantillaRepository { get; }
        IPlantillaSendinblueEtiquetaRepository PlantillaSendinblueEtiquetaRepository { get; }
        IPlantillaSendinblueRepository PlantillaSendinblueRepository { get; }
        IPlantillaSendinblueDatoRepository PlantillaSendinblueDatoRepository { get; }
        IConfiguracionAccesoPersonalRepository ConfiguracionAccesoPersonalRepository { get; }
        IEstadoProgramaEspecificoRepository EstadoProgramaEspecificoRepository { get; }
        ICriteriosEvaluacionProgramasEspecificosRepository CriteriosEvaluacionProgramasEspecificosRepository { get; }
        IPEspecificoCriterioEvaluacionRepository PEspecificoCriterioEvaluacionRepository { get; }
        IReporteIndicadoresProductividadRepository ReporteIndicadoresProductividadRepository { get; }
        IReporteFurPorPagarRepository ReporteFurPorPagarRepository { get; }
        IReporteCambiosCodigosCuotasRepository ReporteCambiosCodigosCuotasRepository { get; }
        IQuejaSugerenciaRepository QuejaSugerenciaRepository { get; }
        IPreguntaIntentoDetalleRepository PreguntaIntentoDetalleRepository { get; }
        IRespuestaPreguntaProgramaCapacitacionRepository RespuestaPreguntaProgramaCapacitacionRepository { get; }
        IPreguntaIntentoRepository PreguntaIntentoRepository { get; }
        IPgeneralAsubPgeneralVersionProgramaRepository PgeneralAsubPgeneralVersionProgramaRepository { get; }
        IProgramaGeneralBeneficioModalidadRepository ProgramaGeneralBeneficioModalidadRepository { get; }
        IProgramaGeneralCertificacionModalidadRepository ProgramaGeneralCertificacionModalidadRepository { get; }
        IPortalWebRepository PortalWebRepository { get; }
        IProgramaGeneralModeloCertificadoModalidadRepository ProgramaGeneralModeloCertificadoModalidadRepository { get; }
        IProgramaGeneralMotivacionModalidadRepository ProgramaGeneralMotivacionModalidadRepository { get; }
        IReporteConsultasForoAulaVirtualRepository ReporteConsultasForoAulaVirtualRepository { get; }
        IContenidoCertificadoIrcaRepository ContenidoCertificadoIrcaRepository { get; }
        IPreguntaTipoRepository PreguntaTipoRepository { get; }
        ITipoRespuestaCalificacionRepository TipoRespuestaCalificacionRepository { get; }
        IEsquemaEvaluacionPgeneralDetalleRepository EsquemaEvaluacionPgeneralDetalleRepository { get; }
        IPgeneralConfiguracionPlantillaEstadoMatriculaRepository PgeneralConfiguracionPlantillaEstadoMatriculaRepository { get; }
        IPgeneralConfiguracionPlantillaSubEstadoMatriculaRepository PgeneralConfiguracionPlantillaSubEstadoMatriculaRepository { get; }
        IConfiguracionBeneficioProgramaGeneralSubEstadoRepository ConfiguracionBeneficioProgramaGeneralSubEstadoRepository { get; }
        IConfiguracionBeneficioProgramaGeneralEstadoMatriculaRepository ConfiguracionBeneficioProgramaGeneralEstadoMatriculaRepository { get; }
        IEsquemaEvaluacionDetalleRepository EsquemaEvaluacionDetalleRepository { get; }
        IConfiguracionBeneficioProgramaGeneralPaisRepository ConfiguracionBeneficioProgramaGeneralPaisRepository { get; }
        IConfiguracionBeneficioProgramaGeneralDatoAdicionalRepository ConfiguracionBeneficioProgramaGeneralDatoAdicionalRepository { get; }
        IConfiguracionBeneficioProgramaGeneralVersionRepository ConfiguracionBeneficioProgramaGeneralVersionRepository { get; }
        IMaterialCriterioVerificacionDetalleRepository MaterialCriterioVerificacionDetalleRepository { get; }
        IRespuestaPreguntaRepository RespuestaPreguntaRepository { get; }
        IPreguntumRepository PreguntumRepository { get; }
        IPartnerContactoPwRepository PartnerContactoPwRepository { get; }
        IPartnerBeneficioPwRepository PartnerBeneficioPwRepository { get; }
        IScrapingAerolineaResultadoRepository ScrapingAerolineaResultadoRepository { get; }
        IScrapingAerolineaResultadoDetalleRepository ScrapingAerolineaResultadoDetalleRepository { get; }
        IScrapingAerolineaConfiguracionRepository ScrapingAerolineaConfiguracionRepository { get; }
        IScrapingAerolineaEstadoConsultaRepository ScrapingAerolineaEstadoConsultaRepository { get; }
        IFlujoRepository FlujoRepository { get; }
        IFlujoActividadRepository FlujoActividadRepository { get; }
        IFlujoFaseRepository FlujoFaseRepository { get; }
        IFlujoOcurrenciaRepository FlujoOcurrenciaRepository { get; }
        IFlujoPorPespecificoRepository FlujoPorPespecificoRepository { get; }
        IMaterialEnvioRepository MaterialEnvioRepository { get; }
        IMaterialEnvioDetalleRepository MaterialEnvioDetalleRepository { get; }
        IMaterialEstadoRecepcionRepository MaterialEstadoRecepcionRepository { get; }
        ICertificadoPartnerComplementoRepository CertificadoPartnerComplementoRepository { get; }
        ITipoDocumentoRepository TipoDocumentoRepository { get; }
        ICoordinadoraRepository CoordinadoraRepository { get; }
        ICalidadProcesamientoAlternoRepository CalidadProcesamientoAlternoRepository { get; }
        IContadorBicRepository ContadorBicRepository { get; }
        IContadorBicLogRepository ContadorBicLogRepository { get; }
        IContadorBicLogDetalleRepository ContadorBicLogDetalleRepository { get; }
        IReportePresupuestoRepository ReportePresupuestoRepository { get; }
        IReporteIngresoRepository ReporteIngresoRepository { get; }
        IPespecificoCursoAdicionalRepository PespecificoCursoAdicionalRepository { get; }
        ICrucigramaProgramaCapacitacionRepository CrucigramaProgramaCapacitacionRepository { get; }
        ICrucigramaProgramaCapacitacionDetalleRepository CrucigramaProgramaCapacitacionDetalleRepository { get; }
        ICarreraPreRequisitoPgeneralRepository CarreraPreRequisitoPgeneralRepository { get; }
        ICicloRepository CicloRepository { get; }
        IPeriodoLectivoRepository PeriodoLectivoRepository { get; }
        IFeedbackConfigurarDetalleRepository FeedbackConfigurarDetalleRepository { get; }
        ICentroCostoCertificadoRepository CentroCostoCertificadoRepository { get; }
        ISexoRepository SexoRepository { get; }
        IReportePendienteMesCoordinadoraRepository ReportePendienteMesCoordinadoraRepository { get; }
        IReporteComprobantesRepository ReporteComprobantesRepository { get; }
        IReporteDocumentosRepository ReporteDocumentosRepository { get; }
        ICongelamientoReporteFlujoRepository CongelamientoReporteFlujoRepository { get; }
        ICongelamientoPeriodoReporteFlujoRepository CongelamientoPeriodoReporteFlujoRepository { get; }
        IReportePendienteV2Repository ReportePendienteV2Repository { get; }
        IReporteFlujoCongeladoPorDiumRepository ReporteFlujoCongeladoPorDiumRepository { get; }
        ICronogramaOriginalesCongeladoPorDiumRepository CronogramaOriginalesCongeladoPorDiumRepository { get; }
        IReportePagoTasaAcademicaRepository ReportePagoTasaAcademicaRepository { get; }
        IConfiguracionPeriodoMatriculaRepository ConfiguracionPeriodoMatriculaRepository { get; }
        IReportePorEstadoMatriculaRepository ReportePorEstadoMatriculaRepository { get; }
        IBandejaPendientePwRepository BandejaPendientePwRepository { get; }
        IModuloSistemaPaqueteRepository ModuloSistemaPaqueteRepository { get; }
        IProcesoPagoIvrRepository ProcesoPagoIvrRepository { get; }
        IReporteTresCxRepository ReporteTresCxRepository { get; }
        ICampaniaGeneralSmsRepository CampaniaGeneralSmsRepository { get; }
        IRecordatorioClasesOnlineIvrRepository RecordatorioClasesOnlineIvrRepository { get; }
        IPuestoTrabajoNivelRepository MaestroNivelPuestoTrabajoRepository { get; }
        IRecordatorioWebinarIvrRepository RecordatorioWebinarIvrRepository { get; }
        IConfiguracionIntegraRepository ConfiguracionIntegraRepository { get; }
        IIvrPlantillaRepository IvrPlantillaRepository { get; }
        IIvrEjecucionRepository IvrEjecucionRepository { get; }
        IIvrTipoConfiguracionRepository IvrTipoConfiguracionRepository { get; }
        ICabeceraConfiguracionLlamadaAutomaticaRepository CabeceraConfiguracionLlamadaAutomaticaRepository { get; }
        IAdwordsRepository AdwordsRepository { get; }
        ILlamadaAutomaticaDetalleCabeceraConfiguracionRepository LlamadaAutomaticaDetalleCabeceraConfiguracionRepository { get; }
        ICategoriaEvaluacionRepository CategoriaEvaluacionRepository { get; }
        ICategoriaPreguntaRepository CategoriaPreguntaRepository { get; }
        IContratoEstadoRepository ContratoEstadoRepository { get; }
        ITipoFormacionRepository TipoFormacionRepository { get; }
        ICriterioEvaluacionProcesoRepository CriterioEvaluacionProcesoRepository { get; }
        IGestionRemuneracionPuestoTrabajoRepository GestionRemuneracionPuestoTrabajoRepository { get; }
        IGestionRemuneracionPuestoTrabajoDetalleRepository GestionRemuneracionPuestoTrabajoDetalleRepository { get; }
        IMaestroEvaluacionRepository MaestroEvaluacionRepository { get; }
        IExamenRepository ExamenRepository { get; }
        IMaestroCursoComplementarioRepository MaestroCursoComplementarioRepository { get; }
        ICompetenciaTecnicaRepository CompetenciaTecnicaRepository { get; }
        ITipoCompetenciaTecnicaRepository TipoCompetenciaTecnicaRepository { get; }
        IReporteIngresoCongelamientoRepository ReporteIngresoCongelamientoRepository { get; }
        IEstadoEtapaProcesoSeleccionRepository EstadoEtapaProcesoSeleccionRepository { get; }
        IPerfilPuestoTrabajoEstadoSolicitudRepository PerfilPuestoTrabajoEstadoSolicitudRepository { get; }
        IExamenFeedbackRepository ExamenFeedbackRepository { get; }
        IFrecuenciaPuestoTrabajoRepository FrecuenciaPuestoTrabajoRepository { get; }
        IGrupoComparacionProcesoSeleccionRepository GrupoComparacionProcesoSeleccionRepository { get; }
        IPostulanteComparacionRepository PostulanteComparacionRepository { get; }
        IPuestoTrabajoGrupoComparacionRepository PuestoTrabajoGrupoComparacionRepository { get; }
        ISedeTrabajoGrupoComparacionRepository SedeTrabajoGrupoComparacionRepository { get; }
        IPostulanteNivelPotencialRepository PostulanteNivelPotencialRepository { get; }
        IPersonalTipoFuncionRepository PersonalTipoFuncionRepository { get; }
        IPersonalRelacionExternaRepository PersonalRelacionExternaRepository { get; }
        IMensajeTiempoInactivoRepository MensajeTiempoInactivoRepository { get; }
        ITipoSangreRepository TipoSangreRepository { get; }
        IEtapaProcesoSeleccionCalificadoRepository EtapaProcesoSeleccionCalificadoRepository { get; }
        IExamenAsignadoRepository ExamenAsignadoRepository { get; }
        IExamenAsignadoEvaluadorRepository ExamenAsignadoEvaluadorRepository { get; }
        IConfiguracionAsignacionEvaluacionRepository ConfiguracionAsignacionEvaluacionRepository { get; }
        IExamenTestRepository ExamenTestRepository { get; }
        IExamenRealizadoRespuestaEvaluadorRepository ExamenRealizadoRespuestaEvaluadorRepository { get; }
        ITipoDocumentacionPersonalRepository TipoDocumentacionPersonalRepository { get; }
        ITipoEstudioRepository TipoEstudioRepository { get; }
        IPostulanteProcesoSeleccionRepository PostulanteProcesoSeleccionRepository { get; }
        ITokenPostulanteProcesoSeleccionRepository TokenPostulanteProcesoSeleccionRepository { get; }
        IWhatsAppMensajeEnviadoPostulanteRepository WhatsAppMensajeEnviadoPostulanteRepository { get; }
        IWhatsAppMensajeRecibidoPostulanteRepository WhatsAppMensajeRecibidoPostulanteRepository { get; }
        IPostulanteFormacionRepository PostulanteFormacionRepository { get; }
        IPostulanteFormacionLogRepository PostulanteFormacionLogRepository { get; }
        IPostulanteExperienciaRepository PostulanteExperienciaRepository { get; }
        IPostulanteExperienciaLogRepository PostulanteExperienciaLogRepository { get; }
        IPostulanteLogRepository PostulanteLogRepository { get; }
        IPuestoTrabajoRepository PuestoTrabajoRepository { get; }
        IGrupoComponenteEvaluacionRepository GrupoComponenteEvaluacionRepository { get; }
        IPostulanteIdiomaRepository PostulanteIdiomaRepository { get; }
        IPostulanteEquipoComputoRepository PostulanteEquipoComputoRepository { get; }
        IPostulanteCursoPortalNotasHistoricoRepository PostulanteCursoPortalNotasHistoricoRepository { get; }
        IConfiguracionAsignacionExamenRepository ConfiguracionAsignacionExamenRepository { get; }
        IPostulanteAccesoTemporalAulaVirtualRepository PostulanteAccesoTemporalAulaVirtualRepository { get; }
        IPersonalAccesoTemporalAulaVirtualRepository PersonalAccesoTemporalAulaVirtualRepository { get; }
        IProcesoSeleccionEtapaRepository ProcesoSeleccionEtapaRepository { get; }
        ICentilRepository CentilRepository { get; }
        IFormulaPuntajeRepository FormulaPuntajeRepository { get; }
        IAsignacionPreguntaExamenRepository AsignacionPreguntaExamenRepository { get; }
        IWolkboxRepository WolkboxRepository { get; }
        IMunicipioRepository MunicipioRepository { get; }
        IAsentamientoMunicipioRepository AsentamientoMunicipioRepository { get; }
        ILinkedInApiRepository LinkedInApiRepository { get; }
        IWhatsAppUsuarioRepository WhatsAppUsuarioRepository { get; }
        IWhatsAppConfiguracionApiRepository WhatsAppConfiguracionApiRepository { get; } 
        IDepartamentoPaiRepository DepartamentoPaiRepository { get; }
        ICiudadDepartamentoPaiRepository CiudadDepartamentoPaiRepository { get; }
        ISiigoApiRepository SiigoApiRepository { get; }
        IProgramaGeneralPresentacionArgumentoRepository ProgramaGeneralPresentacionArgumentoRepository  { get; }
        IProgramaGeneralPresentacionArgumentoModalidadRepository ProgramaGeneralPresentacionArgumentoModalidadRepository { get; }
        IProgramaGeneralPresentacionArgumentoDetalleSolucionRepository ProgramaGeneralPresentacionArgumentoDetalleSolucionRepository { get; }
        IFormularioProgresivoRepository FormularioProgresivoRepository { get; }
        IFormularioProgresivoTipoRepository FormularioProgresivoTipoRepository { get; }
        IFormularioProgresivoCondicionMostrarRepository FormularioProgresivoCondicionMostrarRepository { get; }
        IFormularioProgresivoAccionBotonRepository FormularioProgresivoAccionBotonRepository { get; }
        IFormularioProgresivoSeccionPortalRepository FormularioProgresivoSeccionPortalRepository { get; }
        IFormularioProgresivoConfiguracionBotonRepository FormularioProgresivoConfiguracionBotonRepository { get; }
        ILlamadaWavixWebhookRepository LlamadaWavixWebhookRepository { get; }
        IProcesoSeleccionRangoRepository ProcesoSeleccionRangoRepository { get; }
        IPerfilPuestoTrabajoRepository PerfilPuestoTrabajoRepository { get; }
        IPuestoTrabajoFuncionRepository PuestoTrabajoFuncionRepository { get; }
        IPuestoTrabajoReporteRepository PuestoTrabajoReporteRepository { get; }
        IPuestoTrabajoCursoComplementarioRepository PuestoTrabajoCursoComplementarioRepository { get; }
        IPuestoTrabajoExperienciaRepository PuestoTrabajoExperienciaRepository { get; }
        IPuestoTrabajoCaracteristicaPersonalRepository PuestoTrabajoCaracteristicaPersonalRepository { get; }
        IPuestoTrabajoFormacionAcademicaRepository PuestoTrabajoFormacionAcademicaRepository { get; }
        IPuestoTrabajoPuntajeCalificacionRepository PuestoTrabajoPuntajeCalificacionRepository { get; }
        IEstadoCivilRepository EstadoCivilRepository { get; }
        IPuestoTrabajoRelacionDetalleRepository PuestoTrabajoRelacionDetalleRepository { get; }
        IPuestoTrabajoRelacionRepository PuestoTrabajoRelacionRepository { get; }
        IModuloSistemaPuestoTrabajoRepository ModuloSistemaPuestoTrabajoRepository { get; }
        IModuloSistemaAccesoRepository ModuloSistemaAccesoRepository { get; }
        IPersonalPuestoSedeHistoricoRepository PersonalPuestoSedeHistoricoRepository { get; }
        IEntidadSistemaPensionarioRepository EntidadSistemaPensionarioRepository { get; }
        ITipoDocumentoPersonalRepository TipoDocumentoPersonalRepository { get; }
        IMotivoCeseRepository MotivoCeseRepository { get; }
        IEntidadSeguroSaludRepository EntidadSeguroSaludRepository { get; }
        INivelIdiomaRepository NivelIdiomaRepository { get; }
        IParentescoPersonalRepository ParentescoPersonalRepository { get; }
        ITipoPagoRemuneracionRepository TipoPagoRemuneracionRepository { get; }
        IMotivoInactividadRepository MotivoInactividadRepository { get; }
        ISistemaPensionarioRepository SistemaPensionarioRepository { get; }
        IMelissaRepository MelissaRepository { get; }
        IFacturamaRepository FacturamaRepository { get; }
        IPersonalRemuneracionRepository PersonalRemuneracionRepository { get; }
        IPersonalCeseRepository PersonalCeseRepository { get; }

        IPersonalFormacionRepository PersonalFormacionRepository { get; }
        IPersonalComputoRepository PersonalComputoRepository { get; }
        IPersonalIdiomaRepository PersonalIdiomaRepository { get; }
        IPersonalCertificacionRepository PersonalCertificacionRepository { get; }

        IPersonalExperienciaRepository PersonalExperienciaRepository { get; }
        IPersonalInformacionMedicaRepository PersonalInformacionMedicaRepository { get; }
        IPersonalHistorialMedicoRepository PersonalHistorialMedicoRepository { get; }
        IPersonalSistemaPensionarioRepository PersonalSistemaPensionarioRepository { get; }
        IPersonalSeguroSaludRepository PersonalSeguroSaludRepository { get; }
        IDatoFamiliarPersonalRepository DatoFamiliarPersonalRepository { get; }
        IDatoContratoPersonalRepository DatoContratoPersonalRepository { get; }
        IPersonalLogRepository PersonalLogRepository { get; }
        IPersonalMotivoTiempoInactividadRepository PersonalMotivoTiempoInactividadRepository { get; }
        IPersonalDireccionRepository PersonalDireccionRepository { get; }
        IPersonalArchivoRepository PersonalArchivoRepository { get; }

        IAsesorMarcadorRepository AsesorMarcadorRepository { get; }
        IGrabacionesClasesOnlineRepository GrabacionesClasesOnlineRepository { get; }
        IConfiguracionResumenGrabacionOnlineRepository ConfiguracionResumenGrabacionOnlineRepository { get; }
        IResumenGrabacionOnlineRepository ResumenGrabacionOnlineRepository { get; }
        IPerfilPuestoTrabajoPersonalAprobacionRepository PerfilPuestoTrabajoPersonalAprobacionRepository { get; }
        IDatoContratoComisionBonoRepository DatoContratoComisionBonoRepository { get; }


        //victor hinojosa
        ICentralLlamadaDireccionRepository CentralLlamadaDireccionRepository { get; }
        IEvaluacionCategoriaRepository EvaluacionCategoriaRepository { get; }

        IPEspecificoCodigoPartnerRepository PEspecificoCodigoPartnerRepository { get; }
        IMatriculaFormularioProgresivoRepository MatriculaFormularioProgresivoRepository { get; }

        IProcesoSeleccionPuntajeCalificacionRepository ProcesoSeleccionPuntajeCalificacionRepository { get; }



        ICriterioCalificacionFaseRepository CriterioFaseRepository { get; }
        IGenericRepository<TCriticidadCalificacion> CriticidadCalificacionRepository { get; }

        ITransicionCalificacionFaseRepository TransicionFaseRepository { get; }
        ILineamientoCalificacionFaseRepository LineamientoCalificacionFaseRepository { get; }
    }
}