namespace BSI.Integra.Aplicacion.DTO.Modelos.IntegraDB
{
    public class AsignacionAutomaticaDTO
    {
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public int? IdCentroCosto { get; set; }
        public string NombrePrograma { get; set; }
        public int? IdTipoDato { get; set; }
        public int? IdOrigen { get; set; }
        public int? IdFaseOportunidad { get; set; }
        public int? IdAreaFormacion { get; set; }
        public int? IdAreaTrabajo { get; set; }
        public int? IdIndustria { get; set; }
        public int? IdCargo { get; set; }
        public int? IdPais { get; set; }
        public int? IdCiudad { get; set; }
        public bool? Validado { get; set; }
        public bool? Corregido { get; set; }
        public string OrigenCampania { get; set; }
        public int? IdConjuntoAnuncio { get; set; }
        public int? IdAnuncioFacebook { get; set; }
        public int? IdCategoriaOrigen { get; set; }
        public int? IdAsignacionAutomaticaOrigen { get; set; }
        public int? IdAsignacionAutomaticaTemp { get; set; }
        public int? IdCampaniaScoring { get; set; }
        public DateTime? FechaRegistroCampania { get; set; }
        public Guid? IdFaseOportunidadPortal { get; set; }
        public int? IdOportunidad { get; set; }
        public int? IdPersonal { get; set; }
        public int? IdTiempoCapacitacion { get; set; }
        public int? IdCategoriaDato { get; set; }
        public int? IdTipoInteraccion { get; set; }
        public int? IdSubCategoriaDato { get; set; }
        public int? IdInteraccionFormulario { get; set; }
        public string UrlOrigen { get; set; }
        public double? ProbabilidadActual { get; set; }
        public string ProbabilidadActualDesc { get; set; }
        public int? IdPagina { get; set; }
        public DateTime? FechaProgramada { get; set; }
        public int? IdAlumno { get; set; }
        public Guid? IdMigracion { get; set; }

        public int? idClasificacionPersona { get; set; }

        public string Error { get; set; }
        public bool AptoProcesamiento { get; set; } = true;
    }

    public class AsignacionAutomaticaCompuestoImportadosDTO
    {
        public int TotalRegistros { get; set; }
        public string Alumno { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string CentroCosto { get; set; }
        public string TipoDato { get; set; }
        public string Origen { get; set; }
        public string CodigoFase { get; set; }
        public string AreaFormacion { get; set; }
        public string AreaTrabajo { get; set; }
        public string Industria { get; set; }
        public string Cargo { get; set; }
        public string NombrePais { get; set; }
        public string NombreCiudad { get; set; }
        public string origenCampania { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public decimal? ProbabilidadActual { get; set; }
        public string NombreProbabilidadActual { get; set; }
    }
    public class AsignacionAutomaticaCompuestoDuplicadosDTO
    {
        public int TotalRegistros { get; set; }
        public int Id { get; set; }
        public int? IdAlumno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string CentroCosto { get; set; }
        public int? IdCentroCosto { get; set; }
        public string NombrePrograma { get; set; }
        public string Tipodato { get; set; }
        public int? IdTipodato { get; set; }
        public string Origen { get; set; }
        public int? IdOrigen { get; set; }
        public string CodigoFase { get; set; }
        public int? IdFaseOportunidad { get; set; }
        public string Formacion { get; set; }
        public int? IdAreaFormacion { get; set; }
        public string Trabajo { get; set; }
        public int? IdAreaTrabajo { get; set; }
        public string Industria { get; set; }
        public int? IdIndustria { get; set; }
        public string Cargo { get; set; }
        public int? IdCargo { get; set; }
        public string NombrePais { get; set; }
        public int? IdPais { get; set; }
        public string NombreCiudad { get; set; }
        public int? IdCiudad { get; set; }
        public bool? Validado { get; set; }
        public bool? Corregido { get; set; }
        public string OrigenCampania { get; set; }
        public string IdCampaniaScoring { get; set; }
        public int? IdCategoriaOrigen { get; set; }
        public int? IdAsignacionAutomaticaOrigen { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public DateTime? FechaRegistroCampania { get; set; }
        public string IdFaseOportunidadPortal { get; set; }
    }
    public class AsignacionAutomaticaCompuestoErroneosDTO
    {
        public int TotalRegistros { get; set; }
        public int Id { get; set; }
        public int? IdAlumno { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string CentroCosto { get; set; }
        public int? IdCentroCosto { get; set; }
        public string NombrePrograma { get; set; }
        public string Tipodato { get; set; }
        public int? IdTipodato { get; set; }
        public string Origen { get; set; }
        public int? IdOrigen { get; set; }
        public string CodigoFase { get; set; }
        public int? IdFaseOportunidad { get; set; }
        public string Formacion { get; set; }
        public int? IdAreaFormacion { get; set; }
        public string Trabajo { get; set; }
        public int? IdAreaTrabajo { get; set; }
        public string Industria { get; set; }
        public int? IdIndustria { get; set; }
        public string Cargo { get; set; }
        public int? IdCargo { get; set; }
        public string NombrePais { get; set; }
        public int? IdPais { get; set; }
        public string NombreCiudad { get; set; }
        public int? IdCiudad { get; set; }
        public string OrigenCampania { get; set; }
        public int? IdCampaniaScoring { get; set; }
        public int? IdCategoriaOrigen { get; set; }
        public int? IdAsignacionAutomaticaOrigen { get; set; }
        public DateTime? FechaProgramada { get; set; }
        public DateTime? FechaCreacion { get; set; }
        public DateTime? FechaRegistroCampania { get; set; }
        public string IdFaseOportunidadPortal { get; set; }
        public int? IdPersonal { get; set; }
        public int? IdCategoriaDato { get; set; }
        public int? IdTipoInteraccion { get; set; }
        public int? IdSubCategoriaDato { get; set; }
        public int? IdInteraccionFormulario { get; set; }
        public int? IdAsignacionAutomaticaTipoError { get; set; }
        public bool? EStadoAsignacion { get; set; }
        public bool? EstadoError { get; set; }
        public List<AsignacionAutomaticaErrorDTO> Errores { get; set; }
    }
    public class AsignacionAutomaticaCompuestoDTO
    {
        public int Id { get; set; }
        public int? IdAlumno { get; set; }
        public int? IdContacto { get; set; }
        public string? Nombre1 { get; set; }
        public string? Nombre2 { get; set; }
        public string? ApellidoPaterno { get; set; }
        public string? ApellidoMaterno { get; set; }
        public string? Telefono { get; set; }
        public string? Celular { get; set; }
        public string? Email { get; set; }
        public int? IdCentroCosto { get; set; }
        public string? NombrePrograma { get; set; }
        public int? IdTipoDato { get; set; }
        public int? IdOrigen { get; set; }
        public int? IdFaseOportunidad { get; set; }
        public int? IdAreaFormacion { get; set; }
        public int? IdAreaTrabajo { get; set; }
        public int? IdIndustria { get; set; }
        public int? IdCargo { get; set; }
        public int? IdPais { get; set; }
        public int? IdCiudad { get; set; }
        public bool? Validado { get; set; }
        public bool? Corregido { get; set; }
        public string? OrigenCampania { get; set; }
        public int? IdConjuntoAnuncio { get; set; }
        public int? IdCategoriaOrigen { get; set; }
        public int? IdAsignacionAutomaticaOrigen { get; set; }
        public int? IdCampaniaScoring { get; set; }
        public DateTime? FechaRegistroCampania { get; set; }
        public Guid? IdFaseOportunidadPortal { get; set; }
        public int? IdOportunidad { get; set; }
        public int? IdPersonal { get; set; }
        public int? IdTiempoCapacitacion { get; set; }
        public int? IdCategoriaDato { get; set; }
        public int? IdTipoInteraccion { get; set; }
        public int? IdSubCategoriaDato { get; set; }
        public int? IdInteraccionFormulario { get; set; }
        public string? UrlOrigen { get; set; }
        public double? ProbabilidadActual { get; set; }
        public int? LongTelefono { get; set; }
        public int? LongCelular { get; set; }
        public string? ProbabilidadActualDesc { get; set; }
        public int? IdPagina { get; set; }
        public DateTime? FechaProgramada { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? idClasificacionPersona { get; set; }
        public string? Usuario { get; set; }
        public string? UsuarioModificacion { get; set; }
        public bool? Estado { get; set; }
    }
    public class AsignacionAutomaticaEnvioDTO
    {
        public int Id { get; set; }
        public int? IdAlumno { get; set; }
        public int? IdContacto { get; set; }
        public string? Nombre1 { get; set; }
        public string? Nombre2 { get; set; }
        public string? ApellidoPaterno { get; set; }
        public string? ApellidoMaterno { get; set; }
        public string? Telefono { get; set; }
        public string? Celular { get; set; }
        public string? Email { get; set; }
        public int? IdCentroCosto { get; set; }
        public string? NombrePrograma { get; set; }
        public int? IdTipoDato { get; set; }
        public int? IdOrigen { get; set; }
        public int? IdFaseOportunidad { get; set; }
        public int? IdAreaFormacion { get; set; }
        public int? IdAreaTrabajo { get; set; }
        public int? IdIndustria { get; set; }
        public int? IdCargo { get; set; }
        public int? IdPais { get; set; }
        public int? IdCiudad { get; set; }
        public bool? Validado { get; set; }
        public bool? Corregido { get; set; }
        public string? OrigenCampania { get; set; }
        public int? IdConjuntoAnuncio { get; set; }
        public int? IdCategoriaOrigen { get; set; }
        public int? IdAsignacionAutomaticaOrigen { get; set; }
        public int? IdCampaniaScoring { get; set; }
        public DateTime? FechaRegistroCampania { get; set; }
        public Guid? IdFaseOportunidadPortal { get; set; }
        public int? IdOportunidad { get; set; }
        public int? IdPersonal { get; set; }
        public int? IdTiempoCapacitacion { get; set; }
        public int? IdCategoriaDato { get; set; }
        public int? IdTipoInteraccion { get; set; }
        public int? IdSubCategoriaDato { get; set; }
        public int? IdInteraccionFormulario { get; set; }
        public string? UrlOrigen { get; set; }
        public double? ProbabilidadActual { get; set; }
        public int? LongTelefono { get; set; }
        public int? LongCelular { get; set; }
        public string? ProbabilidadActualDesc { get; set; }
        public int? IdPagina { get; set; }
        public DateTime? FechaProgramada { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? idClasificacionPersona { get; set; }
        public string? Usuario { get; set; }
        public string? UsuarioModificacion { get; set; }
        public bool? Estado { get; set; }
    }
    public class VerificacarManualmemnteDatosDTO
    {
        public int Id { get; set; }
        public int? IdAlumno { get; set; }
        public int? IdContacto { get; set; }
        public string? Nombre1 { get; set; }
        public string? Nombre2 { get; set; }
        public string? ApellidoPaterno { get; set; }
        public string? ApellidoMaterno { get; set; }
        public string? Telefono { get; set; }
        public string? Celular { get; set; }
        public string? Email { get; set; }
        public int? IdCentroCosto { get; set; }
        public string? NombrePrograma { get; set; }
        public int? IdTipoDato { get; set; }
        public int? IdOrigen { get; set; }
        public int? IdFaseOportunidad { get; set; }
        public int? IdAreaFormacion { get; set; }
        public int? IdAreaTrabajo { get; set; }
        public int? IdIndustria { get; set; }
        public int? IdCargo { get; set; }
        public int? IdPais { get; set; }
        public int? IdCiudad { get; set; }
        public bool? Validado { get; set; }
        public bool? Corregido { get; set; }
        public string? OrigenCampania { get; set; }
        public int? IdConjuntoAnuncio { get; set; }
        public int? IdCategoriaOrigen { get; set; }
        public int? IdAsignacionAutomaticaOrigen { get; set; }
        public int? IdCampaniaScoring { get; set; }
        public DateTime? FechaRegistroCampania { get; set; }
        public Guid? IdFaseOportunidadPortal { get; set; }
        public int? IdOportunidad { get; set; }
        public int? IdPersonal { get; set; }
        public int? IdTiempoCapacitacion { get; set; }
        public int? IdCategoriaDato { get; set; }
        public int? IdTipoInteraccion { get; set; }
        public int? IdSubCategoriaDato { get; set; }
        public int? IdInteraccionFormulario { get; set; }
        public string? UrlOrigen { get; set; }
        public double? ProbabilidadActual { get; set; }
        public int? LongTelefono { get; set; }
        public int? LongCelular { get; set; }
        public string? ProbabilidadActualDesc { get; set; }
        public int? IdPagina { get; set; }
        public DateTime? FechaProgramada { get; set; }
        public DateTime? FechaModificacion { get; set; }
        public int? idClasificacionPersona { get; set; }
        public string? Usuario { get; set; }
        public string? UsuarioModificacion { get; set; }
        public bool? Estado { get; set; }
    }

}
