using BSI.Integra.Aplicacion.DTO;
using BSI.Integra.Aplicacion.DTO.Modelos.IntegraDB;
using BSI.Integra.Aplicacion.DTO.Modelos.IntegraDB.Planificacion;
using BSI.Integra.Aplicacion.DTO.SCode.Modelos.IntegraDB.Planificacion;
using BSI.Integra.Persistencia.Entidades.IntegraDB;
using BSI.Integra.Persistencia.Entidades.IntegraDB.Planificacion;

namespace BSI.Integra.Aplicacion.Transversal.Service.Interface
{
    public interface IPGeneralService
    {
        IEnumerable<PGeneralComboDTO> ObtenerCombo();
        IEnumerable<DTO.ComboDTO> ObtenerPGeneralLanzamientoPorEjecucion();
        IEnumerable<PGeneralAlternoDTO> ObtenerPGeneral();
        PGeneralCabeceraSpeechAgendaDTO ObtenerCabeceraSpeechAgenda(int idOportunidad, int idCentroCosto);
        IEnumerable<PGeneralPublicoObjetivoParaAgendaDTO> ObtenerPublicoObjetivoProgramaParaAgenda(int idCentroCosto, int idOportunidad);
        PGeneralAtributosPrincipalesDTO ObtenerPGeneralAtributosPrincipalesPorId(int idPGeneral);
        PgeneralDocumentoSeccionDTO ObtenerPgeneralDocumentoPorId(int id);
        PGeneralNombreDTO ObtenerPGeneralPorIdBusqueda(int idBusqueda);
        PGeneralAreaSubAreaDTO ObtenerPGeneralPEspecificoPorCentroCosto(int idCentroCosto);
        List<PadrePespecificoHijoDTO> ObtenerPadreHijoEspecificoV2(int idPGeneral);
        List<FrecuenciaProgramaGeneralDTO> ObtenerFrecuenciasPorIdPGeneral(int idPGeneral);
        List<PEspecificoSesionDTO> ObtenerSesionesProgramaGeneralValidadoVisualizacionAgenda(int idPGeneral);
        List<PEspecificoSesionDTO> ObtenerSesionesPorProgramaGeneral(int idPGeneral);
        List<MontoPagoProgramaDTO> ObtenerResumenProgramaV2(Dictionary<string, string> filtros);
        List<ModalidadProgramaDTO> ObtenerModalidadesPorProgramaGeneral(int idPGeneral);
        List<InformacionProgramaDTO> ObtenerSeccionesInformacionProgramaPorProgramaGeneral(int idPGeneral);
        List<CorreosGmailDTO> ObtenerCorreosIdPersonalAprobacion(int idPersonal);
        PGeneralAlternoDTO ObtenerPGeneralPorId(int idPGeneral);
        IEnumerable<PGeneralPrincipalDTO> ObtenerTodoGrid();
        public List<PGeneralProgramaCriticoSubAreaDTO> ObtenerPGeneralProgramaCriticoPorSubArea();
        public IEnumerable<ComboDTO> ObtenerProgramasFiltro();
        string ObtenerBeneficiosVersion(int idMatriculaCabecera);
        string ObtenerVersion(int idMatriculaCabecera);
        string ObtenerDuracionMeses(int idMatriculaCabecera);
        IEnumerable<ProgramaGeneralComboDTO> ProgramaGneralconPEspecifico();
        List<PGeneralCursoIrcaDTO> ObtenerCursosIrcaAlumno(int idMatriculaCabecera);
        ProgramaCentroCostoDTO ObtenerDatosPFrecuentes(int idCentroCosto);
        string ObtenerCodigoPartner(int idMatriculacabecera);
        int? ObtenerPdu(int idMatriculacabecera);
        int? ObtenerPduPorIdPGeneral(int idPGeneral);
        List<PGeneralSubAreaCapacitacionFiltroDTO> ObtenerTodoFiltro();
        List<IdDTO> ObtenerTodosPorIdArea(List<int> listaAreas);
        List<IdDTO> ObtenerTodosPorIdSubArea(List<int> listaSubAreas);
        PGeneral ObtenerPorId(int id);
        ProgramaSeccionIndividualDTO SeccionIndividualPGeneral(int idPGeneral, string seccion);
        CuotasProgramaDTO ObtenerProgramaParaCuotas(int idMatricula);
        PgeneralDocumentoSeccionDTO ObtenePgeneralPorIdBusqueda(int idBusqueda);
        Task<PGeneralComboModuloDTO> ObtenerCombosModuloAsync();
        IEnumerable<PGeneralDTO> ListarProgramaGeneral(FiltroProgramaGeneralDTO dto);
        bool GuardarPerfilContactoPrograma(CompuestoPerfilContactoProgramaDTO dto, string usuario);
        bool GuardarModeloPredictivo(CompuestoModeloPredictivoProgramaDTO dto, string usuario);
        ProgramaGeneralPrerequisito GuardarPreRequisitos(CompuestoPreRequisitoModalidadAlternaDTO dto, string usuario);
        bool AsociarProgramasAsociados(ProgramaRelacionadoDTO dto, string usuario);
        IEnumerable<PGeneralModalidadDTO> ListarModalidadesCurso(int idPGeneral);
        Task<PGeneralComboConfiguracionPlantillaModuloDTO> ObtenerCombosConfiguracionPlantillaAsync();
        PGeneralDTO Insertar(ProgramaGeneralDTO programaGeneralDTO, string usuario);
        PlantillaDocumentoDTO ObtenerDocumentosAsociadosYNoAsociados(int idPGeneral);
        bool ActualizarDocumentosAsociados(DocumentoAsociadoProgramaDTO documentoAsociadoProgramaDTO, string usuario);
        (List<PGeneralProgramaRelacionadoDTO>, List<ComboDTO>) ObtenerRelacionCursos(int idPGeneral);
        List<PGeneralCriterioEvaluacionDTO> ObtenerPGcriteriosEvaluacionAOnline(int idPGeneral);
        List<PGeneralCriterioEvaluacionDTO> ObtenerPGcriteriosEvaluacionOnline(int idPgeneral);
        List<PGeneralCriterioEvaluacionDTO> ObtenerPGcriteriosEvaluacionPresencial(int idPgeneral);
        DetallesProgramasDTO ObtenerDetalleProgramas(int idPGeneral);
        IEnumerable<PGeneralVersionProgramaDetalleDTO> ObtenerDuracionProgramas(int idPGeneral);
        PGeneralComboModuloConfigurarVideoProgramaDTO ObtenerCombosConfigurarVideoPrograma();
        PerfilContactoProgramaDTO ObtenerPerfilContacto(int idPGeneral);
        bool ActualizarEstadoPrograma(int idPrograma, bool estado, string usuario);
        ProgramaGeneralBeneficioDTO GuardarBeneficiosVentas(CompuestoBeneficioModalidadDTO beneficioDTO, string usuario);
        bool EliminarBeneficioVenta(int idProgramaGeneralBeneficio, string usuario);
        List<PGeneralCursoCriterioHijoVistaDTO> ObtenerPPadreCEvaluacionPresencial(int idPgeneral);
        List<PGeneralCursoCriterioHijoVistaDTO> ObtenerPPadreCEvaluacionAonline(int idPgeneral);
        bool ActualizarInsertarPGCEvaluacionHijo(PgeneralCriterioEvaluacionHijoV2DTO dto, string usuario);
        List<PGeneralCursoCriterioHijoVistaDTO> ObtenerPPadreCEvaluacionOnline(int idPgeneral);
        PGeneralCriterioEvaluacionDTO ActualizarInsertarPGCEvaluacion(PGeneralCriterioEvaluacionDTO dto, string usuario);
        bool EliminarCriterioEvaluacion(int idCriterioEvaluacion, string usuario);
        ProgramaGeneralModeloCertificadoDTO GuardarModeloCertificado(CompuestoModeloCertificadoModalidadDTO jsonDTO, string usuario);
        bool EliminarModeloCertificado(int idProgramaGeneralModelo, string usuario);
        ModeloPredictivoProgramaDTO ObtenerModeloPredictivo(int IdProgramaGeneral);
        bool EliminarMotivacionVenta(int idProgramaGeneralMotivacion, string usuario);
        ProgramaGeneralMotivacionDTO GuardarMotivacionesVentas(CompuestoMotivacionModalidadDTO motivacionDTO, string usuario);
        ProgramaGeneralProblemaDTO GuardarProblemasVentas(CompuestoProblemaModalidadDTO problemaDTO, string usuario);
        ConfiguracionBeneficioProgramaGeneralAlternoDTO? ObtenerInformacionBeneficioRequisitpDetalle(int idProgramaGeneral, int idBeneficio);
        bool GuardarBeneficiosPreRequisitos(BeneficioPreRequisitoProgramaDTO jsonDTO, string usuario);
        byte[]? GenerarVistaPreviaCertificado(int idPlantillaF, int idPlantillaP, int idPrograma);
        BeneficioPreRequisitoDTO ObtenerBeneficiosYPreRequisitos(int IdProgramaGeneral);
        PGeneralDTO Actualizar(ProgramaGeneralDTO programaGeneralDTO, string usuario);
        bool ActualizarInformacionBeneficioDetalleRequisito(ConfiguracionBeneficioProgramaGeneralAlternoDTO dto, string usuario);
        public IEnumerable<ProgramaGeneralComboDTO> ProgramaGneralconUrlVersion();
        List<PgeneralConfiguracionPlantillaDTO> ObtenerConfiguracionPlantilla(int IdPGeneral);
    }
}
