using BSI.Integra.Aplicacion.DTO;
using BSI.Integra.Aplicacion.DTO.Modelos.IntegraDB;
using BSI.Integra.Aplicacion.DTO.Modelos.IntegraDB.Planificacion;
using BSI.Integra.Persistencia.Entidades.IntegraDB;
using BSI.Integra.Persistencia.Modelos.IntegraDB;
using static BSI.Integra.Aplicacion.Base.Enums.Enums;

namespace BSI.Integra.Repositorio.Repository.Interface
{
    public interface IMatriculaCabeceraRepository : IGenericRepository<TMatriculaCabecera>
    {
        #region Metodos Base
        TMatriculaCabecera Add(MatriculaCabecera entidad);
        TMatriculaCabecera Update(MatriculaCabecera entidad);
        bool Delete(int id, string usuario);

        IEnumerable<TMatriculaCabecera> Add(IEnumerable<MatriculaCabecera> listadoEntidad);
        IEnumerable<TMatriculaCabecera> Update(IEnumerable<MatriculaCabecera> listadoEntidad);
        bool Delete(IEnumerable<int> listadoIds, string usuario);
        #endregion
        IEnumerable<MatriculaCabeceraDTO> ObtenerMatriculaCabecera();
        MatriculaCabecera ObtenerMatriculaCabeceraPorId(int id);
        IEnumerable<MatriculaCabeceraComboDTO> ObtenerCombo();
        int ObtenerIdMatriculaCabeceraPorAlumnoCentroCosto(int idAlumno, int idCentroCosto);
        MatriculaCabeceraCodigoFechaDTO? ObtenerDatosMatriculaDesdeMontoPagoPorIdOportunidad(int idOportunidad);
        MatriculaCabeceraCodigoFechaDTO? ObtenerDatosMatriculaDesdeClasificacionPersonaPorIdOportunidad(int idOportunidad);
        InformacionMatriculaCabeceraDTO ObtenerInformacionMatriculaCabeceraPorIdCronograma(int idCronograma);
        int ObtenerAlumnoProgramaEspecifico(string codigoMatricula);
        int ObtenerProgramaGeneral(int pespecifico);
        string ObtenerFechaFinalizacion(int idMatriculaCabecera);
        bool ActualizarEstadoMatricula(int idMatriculaCabecera, int idEstadoMatricula, string codigoMatricula);
        List<EstadoMatriculadoDTO> ObtenerEstadoMatriculadoPorAlumno(int idAlumno);
        List<MatriculaDTO> ObtenerMatriculaPorAlumno(int idAlumno);
        EstadoMatriculadoDTO ObtenerEstadoEvaluacionPorCodMatricula(string codigoMatricula);
        List<ComboDTO> ObtenerObservacionMatricula();
        bool ActualizarTMatriculaCabecera(string codigoMatricula, string usuario);
        MatriculaCabeceraDTO ObtenerPorIdMatriculaCabecera(int idMatriculaCabecera);
        DetalleOportunidadOperacionesDTO? ObtenerDetalleMatricula(int id);
        string ObtenerUrlConfirmacionParticipacionSesionWebinar(int id, int cantidadDias);
        string ObtenerPresentacionTrabajoNDias(int id, int cantidadDias);
        string ObtenerPresentacionTrabajoFinalNDias(int id, int cantidadDias);
        string ObtenerSesionesWebinarNDias(int id, int cantidadDias, bool mostrarUrlAcceso);
        string ObtenerSesionesWebinarConfirmadasNDias(int id, int cantidadDias, bool mostrarUrlAcceso);
        List<SesionWebinarDTO> ObtenerSesionesConfirmadasWebinarNDias(int idMatriculaCabecera, int cantidadDias);
        string ObtenerCronogramaAutoEvaluacionCompleto(int id);
        string ObtenerAutoEvaluacionesVencidas(int id);
        string ObtenerAutoEvaluacionesCompletas(int id);
        int ObtenerCantidadAutoEvaluacionesPendientes(int id);
        List<AutoEvaluacionCronogramaDetalleDTO> ObtenerDetalleAutoEvaluacionesVencidas(int id, int cantidadDias, bool esFechaExacta);
        AutoEvaluacionCronogramaDetalleDTO ObtenerDetalleProximaAutoEvaluacion(int id);
        int ObtenerCantidadAutoEvaluacionesVencidas(int id);
        string ObtenerCronogramaPagoCompleto(int id, FormatoHTMLMostrar formatoHTMLMostrar);
        string ObtenerMontoTotal(int id);
        string ObtenerCronogramaPagoCompletoCuotasVencidas(int id);
        int ObtenerCantidadCuotasPendientes(int id);
        string ObtenerCuotasVencidas(int id, int cantidadDias, bool esFechaExacta, int idPlantillaBase);
        int ObtenerMaximaCuota(int id);
        int ObtenerCantidadCuotasVencidas(int id, int cantidadDias, bool esFechaExacta, int idPlantillaBase);
        List<CuotaCronogramaDetalleDTO> ObtenerDetalleCuotasVencidas(int id, int cantidadDias, bool esFechaExacta);
        CuotaCronogramaDetalleDTO ObtenerDetalleProximaCuota(int id);
        string ObtenerDescuentoCuotasPendientesPorPorcentaje(int idMatriculaCabecera, decimal porcentaje);
        List<DetalleCursoActualAulaVirtualDTO> ObtenerCursoActualAlumnoMoodle(int id);
        DetalleAccesoAulaVirtualDTO ObtenerDetalleAccesoAulaVirtual(int id);
        DetalleAccesoPortalWebDTO ObtenerDetalleAccesoDocentePortalWeb(int idProveedor);
        DetalleAccesoPortalWebDTO ObtenerDetalleAccesoPortalWeb(int id);
        int ObtenerProximaSesion(int id, int cantidadDias);
        string ObtenerMaterialesPorMaterialPEspecificoDetalle(List<int> listaIdMaterialPEspecificoDetalle);
        List<SesionWebinarDTO> ObtenerUrlSesionesWebinarNDias(int id, int cantidadDias);
        string ObtenerAutoEvaluacionesVencidasDiasExacto(int id, int cantidadDias, bool esFechaExacta, int idPlantillaBase);
        List<AutoEvaluacionCronogramaDetalleDTO> ObtenerDetalleAutoEvaluacionesVencidaDiaExacto(int id, int cantidadDias, bool esFechaExacta);
        int ObtenerTodoCantidadCuotasVencidas(int id);
        string ObtenerUrlMaterialesPorMaterialPEspecificoDetalle(int idMaterialPEspecificoDetalle);
        CambioCentroCostoDTO ObtenerRegistrosParaActualizar(int idSolicitudOperaciones);
        bool ActualizarCentroCosto(CambioCentroCostoDTO solicitudOperacion);
        CambioCentroCostoDTO ObtenerRegistrosParaActualizarVersion(int idSolicitudOperaciones);
        StringDTO EliminarBeneficiosMatriculaCabeceraIdMatricula(int idMatriculaCabecera);
        StringDTO InsertarBeneficiosMatriculaCabeceraIdMatricula(int idMatriculaCabecera, int nuevoPaquete, int idCronograma);
        List<SubEstadoMatriculaFiltroConfiguracionCoordinadoraDTO> ObtenerSubEstadoMatriculaConfiguracionCoordinadora();
        List<SubEstadoMatriculaFiltroDTO> ObtenerSubEstadoMatricula();
        List<InformacionBeneficioSolicitadoDTO> ObtenerBeneficiosSolicitadosPorMatricula(string codigoMatricula);
        List<MatriculaCabeceraBeneficioDTO> ObtenerBeneficiosCongeladosPorMatricula(string codigoMatricula);
        List<MatriculaCabeceraComboDTO> ObtenerEstadoPgeneralBeneficio(int idPGeneral);
        List<MatriculaCabeceraComboDTO> ObtenerSubEstadoPgeneralBeneficio(int idPGeneral);
        int ObtenerEstadoAlumno(string codigoMatricula);
        int ObtenerSubestadoAlumno(string codigoMatricula);
        List<CursoMoodleDTO> ObtenerCursoMoodle(string codigoMatricula);
        List<CostosAdministrativosDTO> ObtenerCostosAdministrativos(int idMatriculaCabecera);
        List<CodigoMatriculaPEspecificoDTO> ObtenerCodigoMatriculaPEspecificoPorAlumno(int idAlumno);
        List<IdentificadorMatriculaComboDTO> ObtenerIdentificadoresMatriculaComboPorAlumno(int idAlumno);
        List<AlumnoProgramaEspecificoDTO> ObtenerAlumnoProgramaEspecificoLista(int idCabeceraMatricula);
        MatriculaCabeceraCodigoFechaDTO CodigoMatriculaPorIdOportunidad(int idOportunidad);
        List<BeneficioSolicitadoReporteDTO> ObtenerTodoBeneficioSolicitado(FiltroBeneficiosSolicitadosPorAlumnos FiltroReporteSolcitud);
        List<DatoAdicionalPWDTO> ObtenerDatosAdicionalesPorCodigo(int idMatriculaCabeceraBeneficios);
        int EntregarBeneficio(int idMatriculaCabeceraBeneficio, string usuario);
        MatriculaTemporalDTO ObtenerMatriculaPorOportunidad(int idOportunidad);
        CodigoMatriculaStringDTO ObtenerMatriculaPorOportunidadOperaciones(int idOportunidad);
        //List<MatriculaCabeceraComboDTO> ObtenerCodigoMatriculaAutocompleto(string nombre);
        IEnumerable<MatriculaCabeceraComboDTO> ObtenerCodigoMatriculaAutocompleto(string nombre);
        int ModificarGestorDeCobranza(string usuario, string gestor, int idMatriculaCabecera);
        bool ActualizarEstadoMatriculaPorSolicitud(int idSolicitudOperaciones, string nombreEstado);
        bool ActualizarSubEstadoMatriculaPorSolicitud(int idSolicitudOperaciones, string nombreSubEstado);
        MatriculaCabecera? ObtenerPorId(int id);
        DatosAlumnoCoordinadorMatriculaCabeceraDTO ObtenerIdAlumnoCoordinadorAcademico(int idMatriculaCabecera);
        MatriculaCabecera? ObtenerPorCodigoMatricula(string codigoMatricula);
        List<FiltroMatriculaAlumnoDTO> ObtenerAlumnosMatriculados(string codMatricula, string dni);
        ProgramaGeneralMatriculaDTO ObtenerProgramaGeneralPorIdMatricula(int idMatriculaCabecera);
        List<CodigoMatriculaIdStringDTO> ObtenerCodigoMatricula(string Codigo);
        public List<CodigoMatriculaPEspecificoDTO> ObtenerCodigoMatriculaPEspecificoPorAlumnos(int idAlumno);
        public List<AlumnoProgramaEspecificoDTO> ObtenerAlumnoProgramaEspecifico(int idCabeceraMatricula);
        public CodigoMatriculaV2DTO ObtenerIdMatriculaPorCodigo(string Codigo);
        public List<DatosMatriculaDTO> ObtenerDatosMatriculaPorCodigoMatriculaVersion(string codigoMatricula, int? version);
        public List<BeneficiosCodigoMatriculaDTO> ObtenerBeneficiosMatriculaCabecera(string codigoMatricula);
        List<EstadosMatriculaDTO> ObtenerEstadosMatricula();
        IdMatriculaDniDTO obtenerIdMatriculaporDni(string DNI);
        IdMatriculaCorreoDTO obtenerIdMatriculaporCorreo(string correo);
        MatriculaCabeceraComboDTO obtenerIdMatriculaporCodigo(string codigo);
        List<MatriculaPespecificoAlumnoDTO> ObtenerCursosMatriculados(int idMatriculaCabecera);
        public bool desmatricularCurso(int idPespecificoMatriculaAlumno, string usuario);
        public List<AlumnoMatriculaDTO> ObtenerListadoAlumnosMatriculaCodigoPEspecifico(int idProgramaEspecifico);
        public List<AlumnoMatriculaDTO> ObtenerListadoAlumnosMatriculaIdAlumno(int idAlumno);
        public List<AlumnoMatriculaDTO> ObtenerListadoAlumnosMatriculaICodigoMatricula(string codMat);
        public List<AlumnoMatriculaDTO> ObtenerListadoAlumnosMatricula();
        public List<SolicitudCambioDTO> ObtenerSolicitudesCambioCronograma(int idPersonal);
        public CentroCostoNombreDTO ObtenerCentroCostoPorMatricula(int idMatriculaCabecera);
        public bool ExisteMatriculaCabecera(int idAlumno, int idPEspecifico);
        public DatosMatriculaManualDTO ObtenerDatosMatriculaManual(string codigoMatricula);
        public List<BeneficioDatosAdicionalesDTO> ObtenerDatosAdicionalesPgeneralPorIdConfiguracion(int IdConfiguracionBeneficioProgramaGeneral);
        public int ActualizarEstadoMatriculaCabeceraBeneficio(int IdMatriculaCabeceraBeneficio);
        public int PorAprobarSolicitudBeneficio(int IdMatriculaCabeceraBeneficio);
        registroDatosMatriculaCabeceraCompletoDTO obtenerGrupoMatriculaIdPorCurso(int IdMatriculaCabecera, int IdPEspecifico);
        registroDatosMatriculaCabeceraCompletoDTO obtenerGrupoMatriculaIdPorCursoGeneral(int IdMatriculaCabecera, int IdPEspecifico);
        public IntDTO ObtenerSubEstadoPorIdMatricula(int idMatriculaCabecera);
        IntDTO ObtenerCantidadPorIdPespecificoUsuarioCoordinador(int idPEspecifico, string usuarioPersonal);
        MatriculaCabeceraDetallesDTO ObtenerDetallesPorId(int id);
        IEnumerable<ListaCuotaPagoDTO> ObtenerCuotasMatriculaoPorId(int id);
        ResumenCronogramaPagoDTO ObtenerResumenCronogramaCuotaPorId(int id);
        IntDTO ObtenerRegistroMedioPagoPorId(int id);
        IEnumerable<MedioPagoActivoPasarelaDTO> ObtenerListaMedioPagoMatriculaCronograma(bool tieneMedioConfigurado, int id, int idPasarelaPago);
        List<ProyectoPresentadoPorAlumnoDTO> GenerarReporteProyectoPresentadoPorAlumno(ProyectoPresentadoPorAlumnoFiltroDTO filtroReporte);
        string? ObtenerCodigoCertificadoIrca(int idMatriculaCabecera);
        string? ObtenerFechaInicioCapacitacionModuloPespecifico(int idMatriculaCabecera, int idPespecifico);
        string? ObtenerFechaFinCapacitacionModuloPespecifico(int idMatriculaCabecera, int idPespecifico);
        string? ObtenerNotaPromedioModulo(int idMatriculaCabecera, int idCurso);
        List<ValorEnteroDTO> ObtenerAlumnosMatriculaProgramaEspecificoGrupo(int idPEspecifico, int grupo);
        IdMatriculaCelularDTO ObtenerIdMatriculaPorCelular(string celular);
        List<MatriculaAlumnoDTO> ObtenerMatriculaAlumno(int idAlumno);
        List<VersionMatriculaDisponibleDTO> ObtenerVersionDisponibleMatricula(int idMatriculaCabecera);
        VersionMatriculaDTO ObtenerVersionMatricula(int idMatriculaCabecera);
        PaisMatriculaDTO ObtenerPaisMatricula(string CodigoMatricula);
    }
}