using BSI.Integra.Aplicacion.DTO;
using BSI.Integra.Aplicacion.DTO.Modelos.IntegraDB;
using BSI.Integra.Aplicacion.DTO.Modelos.IntegraDB.Comercial;
using BSI.Integra.Aplicacion.DTO.Modelos.IntegraDB.Planificacion;
using BSI.Integra.Persistencia.Entidades.IntegraDB;

namespace BSI.Integra.Repositorio.Repository.Interface
{
    public interface IReporteRepository
    {
        ReporteTasaContactoDTO ObtenerReporteTasaContacto(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<ReporteTasaContactoDTO> ObtenerReporteTasaContactoAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<ReporteTasaContactoDTO> ObtenerReporteTasaContactoTresCxAsync(ReporteCambioFaseFiltroProcesadoDTO filtros, bool esHoy);
        Task<ReporteTasaContactoDTO> ObtenerReporteTasaContactoTresCxV2Async(ReporteCambioFaseFiltroProcesadoDTO filtros, bool esHoy);
        Task<ReporteTasaContactoDTO> ObtenerReporteTasaContactoWhatsappV2Async(ReporteCambioFaseFiltroProcesadoDTO filtros, bool esHoy);
        Task<ReporteConsentimientoWhatsappDTO> ObtenerReporteConsentimientoWhatsappV2Async(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<ReporteTasaContactoDTO> ObtenerReporteTasaContactoTresCxOtroMedioAsync(ReporteCambioFaseFiltroProcesadoDTO filtros, bool esHoy);
        IEnumerable<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseControlBICYEAcumulado(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<IEnumerable<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseControlBICYEAcumuladoAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCalidadProcesamientoDTO> ObtenerReporteCalidadProcesamiento(ReporteCambioFaseFiltrosDTO filtros);
        int ObtenerReporteMetasObtenerTotalIS(ReporteCambioFaseFiltrosDTO filtros);
        Task<int> ObtenerReporteMetasObtenerTotalISAsync(ReporteCambioFaseFiltrosDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseOportunidadAcumulado(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseOportunidadNoAcumulado(ReporteCambioFaseFiltroProcesadoDTO filtros);
        ReporteTasaContactoDTO ObtenerReporteTasaContactoRn2(ReporteCambioFaseFiltroProcedimientoDTO filtros);
        Task<ReporteTasaContactoDTO> ObtenerReporteTasaContactoRn2Async(ReporteCambioFaseFiltroProcedimientoDTO filtros);
        List<ControlCambioDeFaseV2DTO> ObtenerReporteControlCambiodeFase(ReporteCambioFaseFiltrosDTO filtros);
        Task<List<ControlCambioDeFaseV2DTO>> ObtenerReporteControlCambiodeFaseAsync(ReporteCambioFaseFiltrosDTO filtros);
        Task<List<ControlCambioDeFaseV2DTO>> ObtenerReporteControlCambiodeFaseTresCxAsync(ReporteCambioFaseFiltrosDTO filtros, bool esHoy);
        Task<List<ControlCambioDeFaseV2DTO>> ObtenerReporteControlCambiodeFaseTresCxV2Async(ReporteCambioFaseFiltrosDTO filtros, bool esHoy);
        Task<List<ControlOtroMedioDTO>> ObtenerReporteControlCambiodeFaseOtroMedioTresCxV2Async(ReporteCambioFaseFiltrosDTO filtros, bool esHoy);
        Task<ReporteTasaContactoDTO> ObtenerReporteTasaContactoCongeladoAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        ReporteTasaContactoDTO ObtenerReporteTasaContactoRn2Congelado(ReporteCambioFaseFiltroProcedimientoDTO filtros);
        Task<ReporteTasaContactoDTO> ObtenerReporteTasaContactoRn2CongeladoAsync(ReporteCambioFaseFiltroProcedimientoDTO filtros);
        List<ControlCambioDeFaseV2DTO> ObtenerReporteControlCambiodeFaseCongelado(ReporteCambioFaseFiltrosDTO filtros);
        Task<List<ControlCambioDeFaseV2DTO>> ObtenerReporteControlCambiodeFaseCongeladoAsync(ReporteCambioFaseFiltrosDTO filtros);
        Task<ReporteTasaContactoConySinLlamadaDTO> ObtenerReporteTasaContactoConySinLlamadaAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<ReporteTasaContactoConySinLlamadaDTO> ObtenerReporteTasaContactoConySinLlamadaTresCxAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<ReporteTasaContactoConySinLlamadaDTO> ObtenerReporteTasaContactoConySinLlamadaTresCxTotalAsync(ReporteCambioFaseFiltroProcesadoDTO filtros, int estadoSeguimientoWhatsapp);
        Task<ReporteTasaContactoConySinLlamadaDTO> ObtenerReporteTasaContactoConySinLlamadaTresCxV2Async(ReporteCambioFaseFiltroProcesadoDTO filtros, int estadoSeguimientoWhatsapp);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseOportunidadAcumuladoV2(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadAcumuladoV2Async(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadAcumuladoPredictivoAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseOportunidadAcumuladoConLlamada(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadAcumuladoConLlamadaAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadAcumuladoConLlamadaTresCxAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseOportunidadAcumuladoSinLlamada(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadAcumuladoSinLlamadaAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadAcumuladoSinLlamadaTresCxAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteControlAcumuladoRN1yRN(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteControlAcumuladoRN1yRNAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoV2(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoV2Async(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoPredictivoAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoConLlamada(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoConLlamadaAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoConLlamadaTresCxAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoSinLlamada(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoSinLlamadaAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoSinLlamadaTresCxAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        List<ReporteCambiosDeFaseOportunidadDTO> ObtenerReporteControlNoAcumuladoRN1yRN(ReporteCambioFaseFiltroProcesadoDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteControlNoAcumuladoRN1yRNAsync(ReporteCambioFaseFiltroProcesadoDTO filtros);
        IEnumerable<EjecutadasSinCambiodeFaseDTO> ObtenerReporteEjecutadasSinCambiodeFase(ReporteCambioFaseFiltrosDTO filtros);
        Task<IEnumerable<EjecutadasSinCambiodeFaseDTO>> ObtenerReporteEjecutadasSinCambiodeFaseAsync(ReporteCambioFaseFiltrosDTO filtros);
        IEnumerable<ActividadVencidaporTabPorDiaAgrupadoDTO> ObtenerReporteActividadesVencidasporTab(ReporteCambioFaseFiltrosDTO filtros);
        Task<List<ActividadVencidaporTabPorDiaAgrupadoDTO>> ObtenerReporteActividadesVencidasporTabAsync(ReporteCambioFaseFiltrosDTO filtros);
        Task<ReporteTasaDeCambioDTO> ObtenerReporteTasaDeConversionAsync(ReporteCambioFaseFiltrosDTO filtros);
        Task<ReporteTasaDeCambioPredictivoDTO> ObtenerReporteTasaDeConversionPredictivaAsync(ReporteCambioFaseFiltrosDTO filtros);
        List<ReporteCalidadProcesamientoDTO> ObtenerReporteCalidadProcesamientoV2(ReporteCambioFaseFiltrosDTO filtros);
        List<ReporteCalidadProcesamientoAlternoDTO> ObtenerReporteCalidadProcesamientoAlterno(ReporteCambioFaseFiltrosDTO filtros);
        List<DiferenciaLlamadasBloqueDTO> ObtenerReporteDiferenciaLlamadasBloque(ReporteCambioFaseFiltrosDTO filtros);
        (List<ConteoDatosFaseDTO> ConteoDatosFase, DateTimeDTO FechaInicio, DateTimeDTO FechaMomento) ObtenerReporteConteoDatosFase(ReporteCambioFaseFiltrosDTO filtros);
        //List<ConteoDatosFaseDTO> ObtenerReporteConteoDatosFase(ReporteCambioFaseFiltrosDTO filtros);
        List<ReporteContactabilidadDTO> ObtenerReporteContactabilidad(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadAsesorDTO> ObtenerReporteContactabilidadAsesorComparativo(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadDTO> ObtenerReporteContactabilidadV2(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadDTO> ObtenerReporteContactabilidadV2TresCx(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidad3cxAlternoDTO> ObtenerReporteContactabilidadV2TresCxAlterno(ReporteContactabilidadFiltroFinalDTO filtro, bool esHoy);
        List<ReporteContactabilidadDTO> ObtenerReporteContactabilidadCongelado(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadDTO> ObtenerReporteContactabilidadCongeladoTresCx(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadAsesorIndicadoresDTO> ObtenerReporteContactabilidadAsesorComparativoV2(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadAsesorIndicadoresDTO> ObtenerReporteContactabilidadAsesorComparativoV2TresCx(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadMinutosDTO> ObtenerReporteContactabilidadMinutos(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadMinutosDTO> ObtenerReporteContactabilidadMinutosTresCx(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteContactabilidadDTO> ObtenerReporteContactabilidadDesagregado(ReporteContactabilidadFiltroFinalDTO filtro);
        List<ReporteSeguimientoOportunidadDTO> ObtenerReporteSeguimiento(SeguimientoFiltroFinalDTO filtro);
        List<ReporteSeguimientoOportunidadDTO> ObtenerReporteSolicitudesVisualizacion(SeguimientoFiltroFinalDTO filtro);
        List<ReporteSeguimientoOportunidadDTO> ObtenerReporteSolicitudesVisualizacionOperaciones(SeguimientoFiltroFinalDTO filtro);
        ValorIntDTO ObtenerAprobacionSolicitudVisualizacion(AprobacionSolicitudesVisualizacionFiltroDTO aprobacionFiltro);
        List<ReporteRealizadaDataDTO> ObtenerReporteActividadesRealizadas(ReporteActividadesRealizadasFiltrosDTO filtro, DateTime fechaInicio, DateTime fechaFin);
        List<ReporteRealizadaDataDTO> ObtenerReporteActividadesRealizadasCongelado(ReporteActividadesRealizadasFiltrosDTO filtro, DateTime fechaInicio, DateTime fechaFin);
        List<ReporteRealizadaDataDTO> ObtenerReporteActividadesRealizadasOperaciones(ReporteActividadesRealizadasFiltrosDTO filtro, DateTime fechaInicio, DateTime fechaFin);
        ReporteTasaConversionConsolidadaMensualGraficasVistaDTO ReporteTasaConversionConsolidadoAsesoresGraficasMensual(string coordinadores, string asesores, string periodoInicio, string periodoFin);
        ReporteTasaConversionConsolidadaGraficasVistaDTO ReporteTasaConversionConsolidadoAsesoresGraficas(string coordinadores, string asesores, string periodoInicio, string periodoFin);
        List<TCRM_ConsolidadTCAsesores> ReporteTasaConversionConsolidadoAsesores(CentroCostoPorAsesorDTO param);
        ReporteTasaConversionConsolidadaAsesoresAlternoDTO ReporteTasaConversionConsolidadoAsesoresAlterno(string area, string subarea, string pgeneral, string pespecifico, string modalidades, string ciudades, bool fecha, string coordinadores, string asesores, DateTime fechaInicio, DateTime fechaFin);
        List<TCRM_CentroCostoPorAsesorDTO> ObtenerCentroCostoPorAsesor(CentroCostoPorAsesorDTO param);
        public List<TCRM_CentroCostoPorAsesorDTO> ObtenerCentroCostoPorAsesorAlterno(string area, string subarea, string pgeneral, string pespecifico, string modalidades, string ciudades, bool fecha, string coordinadores, string asesores, DateTime fechaInicio, DateTime fechaFin);
        List<DateTime> ObtenerActividadesNoEjecutadas(int idOportunidad);
        List<ReporteSeguimientoOportunidadLogDTO> ObtenerListaOportunidadLog(int idOportunidad);
        List<ReporteSeguimientoOportunidadLogDTO> ObtenerListaOportunidadLogPorIdAlumno(int idAlumno, int idOportunidad, int idPadre);
       OportunidadLogReporteOperacionesDTO ObtenerOportunidadLogReporteSeguimientoV5ATC(int idAlumno, int idOportunidad, int idPadre,int diferenciaHoraria,int pageNumber,int pageSize);
        //List<OportunidadLogReporteSeguimientoDetalleATCDTO> ObtenerListaOportunidadLogPorIdAlumnoATC(int idAlumno, int idOportunidad, int idPadre);
        IEnumerable<OportunidadLogReporteATCDTO> ObtenerOportunidadLogReporteSeguimientoV5Operaciones(int idAlumno, int idOportunidad, int idPadre, int diferenciaHoraria, int numberPage, int pageSize);

        List<ReporteActividadOcurrenciaDTO> ReporteActividadOcurrenciaPorIdAlumno(int idAlumno);
        ReporteSeguimientoOportunidadLogGridDTO ObtenerOportunidadCodigoFaseporIdAlumno(int idAlumno, int idOportunidad);
        List<ReportePendientePeriodoyCoordinadorDTO> ObtenerReportePendientePeriodoYCoordinador(ReportePendienteFiltroDTO filtroPendiente);
        List<ReportePendientesCambiosPorCoordinadorDTO> ObtenerReportePendienteCambiosPorCoordinador(ReportePendienteFiltroDTO filtroPendiente);
        List<ReportePendientesDiferenciasDTO> ObtenerReportePendienteDiferencias(ReportePendienteFiltroDTO filtroPendiente);
        List<ReportePendienteDetallesDTO> ObtenerReportePendienteDetalles(ReportePendienteFiltroDTO filtroPendiente);
        List<ReportePagosDiaPeriodoDTO> ObtenerReportePagosDia(ReportePagosDiaPeriodoFiltroDTO filtroReportePagosDiaPeriodo, DateTime fechainicio, DateTime fechafin);
        List<ReportePagosDiaPeriodoDTO> ObtenerReportePagosPeriodo(ReportePagosDiaPeriodoFiltroDTO filtroReportePagosDiaPeriodo, DateTime fechainicio, DateTime fechafin);
        List<ReporteSeguimientoOportunidadesOperacionesDTO> ObtenerReporteSeguimientoOperaciones(SeguimientoFiltroFinalDTO filtro);
        List<ReporteInscritosCarreraOperacionesDTO> ObtenerReporteSeguimientoInscritosCarreraOperaciones(SeguimientoFiltroFinalDTO filtro);
        List<ReporteSeguimientoOportunidadesModeloDTO> ObtenerReporteSeguimientoProbabilidad(SeguimientoFiltroFinalDTO filtro);
        List<ReporteSeguimientoOportunidadDTO> ObtenerReporteSeguimientoFC(SeguimientoFiltroFinalDTO filtro);
        List<ReporteSeguimientoOportunidadDTO> ObtenerReporteSeguimientoFRC(SeguimientoFiltroFinalDTO filtro);
        List<ReporteAvanceAcademicoEstadoSubestadoPresencialOnlineAonlineDTO> GenerarReporteEstadoAlumnosPagos(string filtro, ReporteTasaConversionConsolidadaFiltroDTO filtros2);
        List<ReporteIndicadoresOperativosDTO> GenerarReporteIndicadoresOperativos(string filtros, ReporteTasaConversionConsolidadaFiltroDTO filtros2);
        List<ReporteIndicadoresOperativosPorDiaCoorinadorDTO> GenerarReporteIndicadoresOperativosPorDiaCoordinadora(string filtro, ReporteTasaConversionConsolidadaFiltroDTO filtros2);
        List<ReporteAvanceAcademicoPresencialOnlineDTO> GenerarReporteEstadoAlumnos2(string filtro, ReporteTasaConversionConsolidadaFiltroDTO filtro2);
        List<ReporteAvanceAcademicoAvanceAcademicoVSPagosDTO> GenerarReporteEstadoAlumnosAvanceAcademicoVSPagos(string filtro, ReporteTasaConversionConsolidadaFiltroDTO filtro2);
        List<ReporteAvanceAcademicoAlumnosPagosAtrasados> GenerarReporteEstadoAlumnosPagosAtrasados(string filtro, ReporteTasaConversionConsolidadaFiltroDTO filtro2);
        public List<PagoAlumnoDTO> ObtenerReportePagoAlumnos(FiltroReportePagoDTO Filtro);
        public List<TCRM_CentroCostoByAsesorDetallesDTO> ObtenerCentroCostoPorAsesorDetalles(string area, string subarea, string pgeneral, string pespecifico, string modalidades, string ciudades, bool fecha, string coordinadores, string asesores, DateTime fechaInicio, DateTime fechaFin);
        List<LlamadaObservadaDTO> ObtenerAcumuladoLlamadasReprogramadasManualmente(ReporteCambioFaseSPFiltrosDTO filtros);
        List<ActividadEjecutadaFaseActualDTO> ObtenerActividadEjecutadaFaseActual(ReporteCambioFaseSPFiltrosDTO filtros);
        List<LlamadaObservadaDTO> ObtenerReporteActividadEjecutadaLlamadaObservada(ReporteCambioFaseSPFiltrosDTO filtros, bool esHoy);
        List<LlamadaObservadaDTO> ObtenerReporteActividadEjecutadaLlamadaObservadaTresCx(ReporteCambioFaseSPFiltrosDTO filtros, bool esHoy);
        List<LlamadaObservadaDTO> ObtenerReporteActividadEjecutadaLlamadaObservadaTresCxV2(ReporteCambioFaseSPFiltrosDTO filtros, bool esHoy);
        List<AcumuladoTiempoContactoEfectivoDTO> ObtenerAcumuladoTiempoContactoEfectivoOportunidadCerradas(ReporteCambioFaseSPFiltrosDTO filtros);
        List<AcumuladoTiempoContactoEfectivoDTO> ObtenerAcumuladoTiempoContactoEfectivoOportunidadCerradasTresCx(ReporteCambioFaseSPFiltrosDTO filtros);
        List<AcumuladoTiempoContactoEfectivoDTO> ObtenerAcumuladoTiempoContactoEfectivoOportunidadAbiertas(ReporteCambioFaseSPFiltrosDTO filtros);
        List<AcumuladoTiempoContactoEfectivoDTO> ObtenerAcumuladoTiempoContactoEfectivoOportunidadAbiertasTresCx(ReporteCambioFaseSPFiltrosDTO filtros);
        List<ReporteProblemasAulaVirtualResultadoDTO> ObtenerReporteProblemasAulaVirtual(ReporteProblemasAulaVirtualFiltroDTO filtro);

        public List<ReporteDevolucionDTO> ObtenerReporteDevoluciones(ReporteDevolucionesFiltroDTO FiltroDevoluciones);
        public int CongelarReporteDeDevoluciones(DateTime FechaCongelamiento, string Usuario);
        public List<ReporteFlujoDTO> ObtenerReporteFlujos(FiltroFechaDTO filtro);
        public List<ReportePagosDTO> ObtenerReportePagos(FiltroFechaDTO filtro);
        public List<ReporteDocumentosPendientesPagoDTO> ObtenerReporteDocumentosPendientesPago();
        public int CongelarReporteDeFlujoPorDia(DateTime FechaCongelamiento, string Usuario);
        public int CongelarReporteDeFlujoPorPeriodo(string Usuario, int IdPeriodo);
        public int CongelarReporteOriginalesPorDia(DateTime FechaCongelamiento, string Usuario);
        public List<ReporteControlDocumentosDTO> ObtenerReporteControlDocumentos(ReporteControlDocumentosFiltroDTO filtroControlDocumentos);
        public List<ReporteComisionesDTO> ObtenerReporteComisiones(FiltroReporteComisionDTO filtro);
        public bool ActualizarReporteComisiones(DateTime FechaInicio, DateTime FechaFin);
        bool ActualizarCronogramaVersionFinal();
        public List<ReportePagosACuentaDTO> ObtenerReportePagosACuenta(string Anios);
        public List<TasaCambioReportePagosDTO> ObtenerTasaCambioReportePagoACuenta(string Anios);
        Task<IEnumerable<EjecutadasSinCambiodeFaseAlternoDTO>> ObtenerActividadesSinCambiodeFaseAlternoAsync(ReporteCambioFaseFiltrosDTO filtros);
        Task<IEnumerable<EjecutadasSinCambiodeFaseAlternoDTO>> ObtenerActividadesSinCambiodeFaseAlternoTresCxAsync(ReporteCambioFaseFiltrosDTO filtros);
        public List<PagosIngresosDTO> ObtenerReportePagosIngresos(ReportePagosPorPeriodoFiltroDTO filtro);
        public int CongelarReporteDePagosPorDia(DateTime FechaCongelamiento, string Usuario);
        public int CongelarReporteDePagosPorPeriodo(DateTime FechaCongelamiento, int IdPeriodo, string Usuario);
        List<ConteoDatosFaseAlternoDTO> ObtenerReporteConteoDatosFaseAlterno(ReporteCambioFaseFiltrosDTO filtros);
        public List<ReportePagoPorAsistenteDTO> ObtenerReportePagoPorAsistente(filtroReportePagoPorAsistenteDTO filtro);


        //TresCx
        List<ReporteSeguimientoOportunidadDTO> ObtenerReporteSeguimientoTresCx(SeguimientoFiltroFinalDTO filtro);
        List<ReporteSeguimientoOportunidadLogTresCxDTO> ObtenerListaOportunidadLogTresCx(int idOportunidad);
        List<ActividadEjecutadaFaseActualDTO> ObtenerActividadEjecutadaFaseActualTresCx(ReporteCambioFaseSPFiltrosDTO filtros);
        List<ControlOportunidadPredictivaDTO> ObtenerControlOportunidadPredictiva(ReporteCambioFaseSPFiltrosDTO filtros);
        List<ReporteLlamadaEntranteDTO> ObtenerReporteLlamadaEntrante(FiltroReporteLlamadaEntranteDTO filtro);

        /*Cambios de fase (nuevo)*/
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadAcumuladoConLlamadaAlternoAsync(ReporteCambioFaseFiltrosDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadAcumuladoSinLlamadaAlternoAsync(ReporteCambioFaseFiltrosDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoConLlamadaAlternoAsync(ReporteCambioFaseFiltrosDTO filtros);
        Task<List<ReporteCambiosDeFaseOportunidadDTO>> ObtenerReporteCambiosDeFaseOportunidadNoAcumuladoSinLlamadaAlternoAsync(ReporteCambioFaseFiltrosDTO filtros);

    }
}
